easyops-cn/next-bricks

bricks/data-view/package.json, bricks/data-view/src/bootstrap.ts, bricks/data-view/src/data-view-variables.shadow.css, bricks/data-view/src/hooks/index.ts, bricks/data-view/src/hooks/useResizeObserver/index.spec.tsx, bricks/data-view/src/hooks/useResizeObserver/index.ts, bricks/data-view/src/hooks/useResizeObserver/resizeObserverUtil.spec.ts, bricks/data-view/src/hooks/useResizeObserver/resizeObserverUtil.ts, bricks/data-view/src/modern-style-treemap/dot.svg, bricks/data-view/src/modern-style-treemap/index.spec.ts, bricks/data-view/src/modern-style-treemap/index.tsx, bricks/data-view/src/modern-style-treemap/modern-style-treemap.shadow.css, bricks/data-view/test.config.js, yarn.lock
Refs DASHBOARD-237
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): brick modern-style-treemap

bricks/data-view/src/data-view-variables.shadow.css
=> chore(): style update

bricks/data-view/src/tabs-drawer/index.spec.tsx, bricks/data-view/src/tabs-drawer/index.tsx, bricks/data-view/src/tabs-drawer/tabs-drawer.shadow.css
refs DASHBOARD-234
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): modify style

package.json, yarn.lock
=> chore(): add missing eslint preset

bricks/data-view/src/battery-chart/battery-chart.shadow.css, bricks/data-view/src/battery-chart/index.spec.tsx, bricks/data-view/src/battery-chart/index.tsx, bricks/data-view/src/bootstrap.ts
refs DASHBOARD-235
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support battery-chart component

bricks/data-view/src/gauge-chart/index.spec.tsx, bricks/data-view/src/gauge-chart/index.tsx
refs DASHBOARD-236
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 当value为100时，如果strokeWidth较大，圆点会被截取

bricks/data-view/src/gauge-chart/index.spec.tsx, bricks/data-view/src/gauge-chart/index.tsx
refs DASHBOARD-236
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): gauge-chart 插槽数据与图表不居中

bricks/advanced/src/table/BrickTable.tsx, bricks/advanced/src/table/index.spec.tsx, bricks/advanced/src/table/index.tsx
请勾选以下两组选项其中之一：
或者：
>
>
- [] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [] 手动验证过新特性可以正常工作。
=> fix(): in one page the second table style miss

bricks/basic/src/select/index.shadow.css, bricks/basic/src/select/index.spec.ts, bricks/basic/src/select/index.tsx
=> feat(): select support input search

bricks/basic/src/checkbox/index.tsx, bricks/basic/src/link/index.spec.tsx, bricks/basic/src/link/index.tsx, bricks/basic/src/modal/index.spec.tsx, bricks/basic/src/modal/index.tsx, bricks/basic/src/radio/index.spec.tsx, bricks/basic/src/radio/index.tsx, bricks/containers/src/category/category.shadow.css
=> feat(): component update and unit test fix

.github/workflows/ci.yml, package.json, scripts/build-gh.mjs
=> chore(): build gh-pages

bricks/data-view/src/modern-style-treemap/example.html, bricks/data-view/src/modern-style-treemap/index.spec.tsx, bricks/data-view/src/modern-style-treemap/index.tsx, bricks/data-view/src/utils/debounceByAnimationFrame.spec.ts, bricks/data-view/src/utils/debounceByAnimationFrame.ts
Refs DASHBOARD-237
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): useBrick data数据没有位置信息

bricks/data-view/src/complex-search/complex-search.shadow.css, bricks/data-view/src/complex-search/example.yaml, bricks/data-view/src/complex-search/i18n.ts, bricks/data-view/src/complex-search/index.spec.tsx, bricks/data-view/src/complex-search/index.tsx, bricks/data-view/src/gauge-chart/example.yaml, bricks/data-view/src/tabs-drawer/example.yaml, bricks/data-view/src/tabs-drawer/tabs-drawer.shadow.css
=> chore(): add i18n & example.yaml

bricks/data-view/src/dropdown-menu/dropdown-menu.shadow.css, bricks/data-view/src/dropdown-menu/index.tsx
=> chore(): Update the style

.github/workflows/ci.yml, bricks/icons/src/antd-icon/index.tsx, bricks/icons/src/easyops-icon/index.tsx, bricks/icons/src/fa-icon/index.tsx, bricks/icons/src/general-icon/example.yaml, bricks/icons/src/general-icon/index.tsx, bricks/icons/src/shared/DefineLinearGradient.shadow.css, bricks/icons/src/shared/DefineLinearGradient.spec.tsx, bricks/icons/src/shared/DefineLinearGradient.tsx
=> feat(): support setting gradient color

bricks/v2-adapter/src/data-providers/load-bricks.ts
=> fix(): legacy fa icons with gradient color

bricks/v2-adapter/src/data-providers/legacy-brick-kit/getLegacyUseBrick.ts, bricks/v2-adapter/src/data-providers/load-bricks.ts
=> fix(): fix legacy useBrick and doTransform

bricks/v2-adapter/src/data-providers/legacy-brick-kit/getLegacyRuntime.ts, bricks/v2-adapter/src/data-providers/load-bricks.ts
=> fix(): add legacy developHelper

bricks/data-view/src/bootstrap.ts, bricks/data-view/src/hooks/index.ts, bricks/data-view/src/hooks/usePrevious/index.ts, bricks/data-view/src/hooks/usePrevious/usePrevious.spec.ts, bricks/data-view/src/loading-panel/example.yaml, bricks/data-view/src/loading-panel/index.spec.tsx, bricks/data-view/src/loading-panel/index.tsx, bricks/data-view/src/loading-panel/loading-panel.shadow.css
refs DASHBOARD-248
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support loading-panel component

bricks/data-view/src/loading-panel/index.tsx
refs DASHBOARD-248
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): modify step

bricks/v2-adapter/src/data-providers/load-bricks.ts
=> fix(): support legacy preview methods of developHelper

bricks/devtools/build.config.js, bricks/devtools/package.json, bricks/devtools/src/bootstrap.ts, bricks/devtools/src/data-providers/preview-start.spec.ts, bricks/devtools/src/data-providers/preview-start.ts, bricks/devtools/src/data-providers/preview/capture.ts, bricks/devtools/src/data-providers/preview/inspector.ts, bricks/devtools/src/data-providers/preview/interfaces.ts, bricks/devtools/src/data-providers/preview/resizeScreenshot.spec.ts, bricks/devtools/src/data-providers/preview/resizeScreenshot.ts, bricks/devtools/src/index.ts, bricks/devtools/tsconfig.json, bricks/icons/package.json, yarn.lock
=> feat(): support preview in visual builder

bricks/data-view/src/app-wall/card-item/card-item.shadow.css, bricks/data-view/src/app-wall/card-item/example.yaml, bricks/data-view/src/app-wall/card-item/index.spec.ts, bricks/data-view/src/app-wall/card-item/index.tsx, bricks/data-view/src/bootstrap.ts
Refs DASHBOARD-269
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): brick data-view.app-wall-card-item

bricks/data-view/src/app-wall/system-card/example.yaml, bricks/data-view/src/app-wall/system-card/index.spec.tsx, bricks/data-view/src/app-wall/system-card/index.tsx, bricks/data-view/src/app-wall/system-card/system-card.shadow.css, bricks/data-view/src/bootstrap.ts
refs DASHBOARD-270
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support system-card component

bricks/basic/src/link/index.spec.tsx, bricks/basic/src/link/index.tsx, bricks/containers/src/modal/index.tsx, bricks/form/src/select/index.tsx
=> feat(): link component update

bricks/data-view/src/app-wall/system-card/example.yaml, bricks/data-view/src/battery-chart/battery-chart.shadow.css, bricks/data-view/src/battery-chart/example.yaml, bricks/data-view/src/battery-chart/index.tsx
=> chore(): update demo

bricks/data-view/src/app-wall/system-card/system-card.shadow.css, bricks/data-view/src/data-view-variables.shadow.css
=> chore(): modify style

bricks/data-view/src/app-wall/relation-line/example.yaml, bricks/data-view/src/app-wall/relation-line/index.spec.ts, bricks/data-view/src/app-wall/relation-line/index.tsx, bricks/data-view/src/app-wall/relation-line/relation-line.shadow.css, bricks/data-view/src/bootstrap.ts
Refs DASHBOARD-271
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): brick data-view.app-wall-relation-line

bricks/advanced/package.json, bricks/basic/package.json, bricks/containers/package.json, bricks/data-view/package.json, bricks/form/package.json, bricks/icons/package.json, bricks/shoelace/package.json, bricks/shoelace/src/data-providers/show-dialog/show-dialog.tsx, bricks/shoelace/src/sl-button/index.ts, bricks/shoelace/src/sl-dialog/index.ts, bricks/shoelace/src/sl-icon/index.ts, bricks/v2-adapter/package.json, yarn.lock
=> fix(): update react-element

bricks/data-view/src/bootstrap.ts, bricks/data-view/src/cabinet/cabinet-button/cabinet-button.shadow.css, bricks/data-view/src/cabinet/cabinet-button/example.yaml, bricks/data-view/src/cabinet/cabinet-button/index.spec.ts, bricks/data-view/src/cabinet/cabinet-button/index.tsx
refs DASHBOARD-299
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): support cabinet-button component

bricks/data-view/src/app-wall/utils.spec.ts, bricks/data-view/src/app-wall/utils.ts
=> fix(): 布局没有居中

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/index.tsx
=> chore(): add helper

bricks/data-view/src/bootstrap.ts, bricks/data-view/src/cabinet/cabinet-container/cabinet-container.shadow.css, bricks/data-view/src/cabinet/cabinet-container/example.yaml, bricks/data-view/src/cabinet/cabinet-container/index.spec.ts, bricks/data-view/src/cabinet/cabinet-container/index.tsx
refs DASHBOARD-292
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(cabinet-container): support cabinet-container component

bricks/data-view/src/cabinet/cabinet-container/index.spec.ts, bricks/data-view/src/cabinet/cabinet-container/index.tsx
refs DASHBOARD-292
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(cabinet-container): 增加监听宽高事件

bricks/data-view/src/cabinet/cabinet-container/cabinet-container.shadow.css, bricks/data-view/src/cabinet/cabinet-container/index.spec.ts, bricks/data-view/src/cabinet/cabinet-container/index.tsx
refs DASHBOARD-292
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(cabinet-container): 增加叠层&布局由于clientWidth四舍五入，导致布局不对

bricks/data-view/src/cabinet/cabinet-container/index.spec.ts, bricks/data-view/src/cabinet/cabinet-container/index.tsx
refs DASHBOARD-292
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(cabinet-container): add click event

bricks/data-view/src/bootstrap.ts, bricks/data-view/src/cabinet/cabinet-button/index.tsx, bricks/data-view/src/cabinet/cabinet.shadow.css, bricks/data-view/src/cabinet/example.yaml, bricks/data-view/src/cabinet/index.spec.ts, bricks/data-view/src/cabinet/index.tsx
Refs: DASHBOARD-295
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): data-view.cabinet-graph

bricks/data-view/src/modern-style-treemap/index.spec.tsx, bricks/data-view/src/modern-style-treemap/index.tsx
Refs: DASHBOARD-320
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 修复启用缩放会导致tooltip位置不准

bricks/data-view/src/dropdown-menu/dropdown-menu.shadow.css, bricks/data-view/src/dropdown-menu/index.spec.ts, bricks/data-view/src/dropdown-menu/index.tsx
Refs: DASHBOARD-319
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): dropdown-menu support allowClear

bricks/data-view/src/app-wall/system-card/index.spec.tsx, bricks/data-view/src/app-wall/system-card/index.tsx, bricks/data-view/src/app-wall/system-card/system-card.shadow.css
Refs: DASHBOARD-322
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 系统卡片更新滚动条需重置回顶部

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/interface.ts, bricks/data-view/src/app-wall/utils.spec.ts, bricks/data-view/src/app-wall/utils.ts, bricks/data-view/src/cabinet/cabinet-thumbnail/cabinet-thumbnail.shadow.css, bricks/data-view/src/cabinet/cabinet-thumbnail/index.spec.tsx, bricks/data-view/src/cabinet/cabinet-thumbnail/index.tsx
refs DASHBOARD-323
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): t台缩放问题& 增加columns 配置

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/utils.spec.ts
Refs DASHBOARD-321
请勾选以下两组选项其中之一：
或者：
>
>
=> test(): 补充utils单测

bricks/data-view/src/app-wall/app-wall.shadow.css, bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/utils.spec.ts, bricks/data-view/src/app-wall/utils.ts, bricks/data-view/src/cabinet/cabinet-thumbnail/cabinet-thumbnail.shadow.css, bricks/data-view/src/cabinet/cabinet-thumbnail/example.yaml, bricks/data-view/src/cabinet/cabinet-thumbnail/index.spec.tsx, bricks/data-view/src/cabinet/cabinet-thumbnail/index.tsx
refs DASHBOARD-323
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): 缩略图遗漏appName

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/index.spec.ts, bricks/data-view/src/app-wall/index.tsx, bricks/data-view/src/app-wall/interface.ts, bricks/data-view/src/app-wall/utils.ts, bricks/data-view/test.config.js
Refs DASHBOARD-316
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 修复点击卡片偶现连线还在的问题

bricks/data-view/src/app-wall/index.spec.ts
=> test(): add test

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/index.spec.ts, bricks/data-view/src/app-wall/interface.ts, bricks/data-view/src/app-wall/utils.ts
Refs DASHBOARD-316
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 修复hover连续触发tween动画导致属性赋值不符合预期

bricks/data-view/src/bootstrap.ts, bricks/data-view/src/graph/text/example.yaml, bricks/data-view/src/graph/text/graph-text.shadow.css, bricks/data-view/src/graph/text/i18n.ts, bricks/data-view/src/graph/text/index.spec.ts, bricks/data-view/src/graph/text/index.tsx
refs DASHBOARD-351
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(graph-text): support graph-text component

bricks/basic/src/link/example.html, bricks/basic/src/link/index.spec.tsx, bricks/basic/src/link/index.tsx
=> feat(): general-link support url

bricks/data-view/src/cabinet/index.tsx
refs DASHBOARD-351
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): support cabinet.click event

bricks/form/src/code-editor/example.html, bricks/form/src/dynamic-form-item/example.html, bricks/form/src/form/example.html, bricks/form/src/select/example.html, bricks/form/src/textarea/example.html, bricks/form/src/textarea/index.spec.tsx, bricks/form/src/textarea/index.tsx, bricks/form/src/textarea/textarea.shadow.css
=> feat(): update textarea with formItem

bricks/basic/src/data-providers/httpRequest.ts, bricks/devtools/src/data-providers/preview-start.ts, bricks/icons/src/bootstrap.ts, bricks/icons/src/data-providers/get-icons.ts, bricks/icons/src/icons.ts, bricks/illustrations/src/data-providers/get-illustration.ts, bricks/illustrations/src/data-providers/get-illustrations-by-category.ts, bricks/shoelace/src/data-providers/show-dialog/show-dialog.tsx, bricks/shoelace/src/data-providers/show-notification/show-notification.ts, bricks/v2-adapter/src/data-providers/load-bricks.ts
=> fix(): separate icon providers

bricks/data-view/src/bootstrap.ts, bricks/data-view/src/graph/layout-grid/example.yaml, bricks/data-view/src/graph/layout-grid/graph-layout-grid.shadow.css, bricks/data-view/src/graph/layout-grid/index.spec.ts, bricks/data-view/src/graph/layout-grid/index.tsx, bricks/data-view/src/graph/node/index.tsx, bricks/data-view/src/graph/text/graph-text.shadow.css, bricks/data-view/src/graph/text/index.tsx
refs DASHBOARD-352
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): support graph-layout-grid component

bricks/data-view/src/complex-search/complex-search.shadow.css, bricks/data-view/src/complex-search/index.tsx
refs DASHBOARD-373
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): 搜索构件tooltip高度展示不对

bricks/data-view/src/app-wall/index.spec.tsx, bricks/data-view/src/bootstrap.ts, bricks/data-view/src/radar-chart/example.yaml, bricks/data-view/src/radar-chart/index.spec.tsx, bricks/data-view/src/radar-chart/index.tsx, bricks/data-view/src/radar-chart/interface.ts, bricks/data-view/src/radar-chart/radar.tsx, bricks/data-view/src/radar-chart/styles.shadow.css, bricks/data-view/src/radar-chart/utils.spec.tsx, bricks/data-view/src/radar-chart/utils.ts
refs DASHBOARD-326
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): 实现雷达图构件

bricks/basic/src/button/button.shadow.css, bricks/basic/src/button/example.html, bricks/basic/src/button/index.spec.ts, bricks/basic/src/button/index.tsx, bricks/basic/src/dropdown-button/example.html, bricks/basic/src/dropdown-button/index.tsx, bricks/basic/src/interface.ts, bricks/basic/src/tag-list/index.tsx, bricks/basic/src/tag/example.html, bricks/basic/src/tag/index.tsx, bricks/basic/src/tag/tag.shadow.css, bricks/containers/src/grid-layout/index.tsx, bricks/containers/src/interface.ts, bricks/containers/src/tab/tab-list/index.tsx, bricks/form/src/input/example.html, bricks/form/src/input/index.tsx, bricks/form/src/input/input.shadow.css, bricks/form/src/interface.ts, bricks/form/src/radio/index.shadow.css, bricks/form/src/radio/index.tsx, bricks/form/src/textarea/index.tsx
=> feat(): replace size middle to medium

bricks/data-view/src/cabinet/cabinet-container/cabinet-container.shadow.css, bricks/data-view/src/cabinet/cabinet-container/index.spec.ts, bricks/data-view/src/cabinet/cabinet-container/index.tsx, bricks/data-view/src/cabinet/cabinet-thumbnail/cabinet-thumbnail.shadow.css, bricks/data-view/src/complex-search/complex-search.shadow.css, bricks/data-view/src/complex-search/index.spec.tsx, bricks/data-view/src/complex-search/index.tsx
refs DASHBOARD-378
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): 搜索构件、部署架构UI调整

bricks/data-view/src/radar-chart/radar.tsx, bricks/data-view/src/radar-chart/styles.shadow.css, bricks/data-view/src/radar-chart/utils.ts
refs DASHBOARD-326
请勾选以下两组选项其中之一：
或者：
>
>
=> style(): 调整样式布局

bricks/data-view/src/modern-style-treemap/index.spec.tsx, bricks/data-view/src/modern-style-treemap/index.tsx, bricks/data-view/src/modern-style-treemap/modern-style-treemap.shadow.css
refs DASHBOARD-376
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): treemap tooltip定位的边界问题

bricks/data-view/src/modern-style-treemap/example.html
=> chore(data-view): Complete treemap example.html

bricks/data-view/src/modern-style-treemap/modern-style-treemap.shadow.css
refs DASHBOARD-376
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): treemap tooltip边界样式修改

bricks/data-view/src/radar-chart/index.tsx, bricks/data-view/src/radar-chart/interface.ts, bricks/data-view/src/radar-chart/radar.tsx
refs DASHBOARD-389
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 雷达图构件适配父元素scale之后的布局

bricks/shoelace/scripts/pre-build.js
=> feat(): add utilities

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/utils.ts
refs DASHBOARD-364
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 调整应用墙构件卡片框大小并修复交互bug

bricks/data-view/src/graph/layout-grid/graph-layout-grid.shadow.css, bricks/data-view/src/graph/layout-grid/index.spec.ts, bricks/data-view/src/graph/layout-grid/index.tsx, bricks/data-view/src/grid-background/grid-background.shadow.css
refs DASHBOARD-392
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): modify graph node animation

bricks/advanced/src/bootstrap.ts, bricks/advanced/src/cascader/index.spec.ts, bricks/advanced/src/cascader/index.tsx
Closes BRICK_STORE-3375
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support advanced.general-cascader

bricks/data-view/src/radar-chart/utils.ts
refs DASHBOARD-393
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): modify style

bricks/data-view/src/cabinet/cabinet-container/index.spec.ts, bricks/data-view/src/cabinet/cabinet-container/index.tsx, bricks/data-view/src/cabinet/index.spec.ts, bricks/data-view/src/cabinet/index.tsx
refs DASHBOARD-403
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): cabinet add dbclick event

bricks/visual-builder/build.config.js, bricks/visual-builder/package.json, bricks/visual-builder/src/bootstrap.ts, bricks/visual-builder/src/index.ts, bricks/visual-builder/src/shared/debounceByAnimationFrame.ts, bricks/visual-builder/src/shared/scrollbar.shadow.css, bricks/visual-builder/src/workbench-pane/example.yaml, bricks/visual-builder/src/workbench-pane/index.spec.ts, bricks/visual-builder/src/workbench-pane/index.tsx, bricks/visual-builder/src/workbench-pane/workbench-pane.shadow.css, bricks/visual-builder/src/workbench-sidebar/example.yaml, bricks/visual-builder/src/workbench-sidebar/index.spec.ts, bricks/visual-builder/src/workbench-sidebar/index.tsx, bricks/visual-builder/src/workbench-sidebar/workbench-sidebar.shadow.css, bricks/visual-builder/tsconfig.json
Refs NEXT_BUILDER-3135
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): workbench-pane and workbench-sidebar

bricks/basic/src/tag-list/example.html, bricks/basic/src/tag-list/index.tsx, bricks/basic/src/tag/index.tsx
=> fix(): tab-list multiple error

bricks/icons/src/fa-icon/index.spec.ts
=> test(): add tests cases for fa-icon

.github/workflows/ci.yml, lerna.json, package.json, shared/general/README.md, shared/general/package.json, shared/general/src/menu.spec.ts, shared/general/src/menu.ts, shared/general/src/types.ts, shared/general/tsconfig.build.json, shared/general/tsconfig.json, yarn.lock
=> feat(): new shared package: @next-shared/general

bricks/data-view/src/graph/text/graph-text.shadow.css, bricks/data-view/src/graph/text/index.spec.ts, bricks/data-view/src/graph/text/index.tsx
refs DASHBOARD-408
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): 文本过长换行

bricks/basic/src/link/index.tsx, bricks/visual-builder/package.json, bricks/visual-builder/src/bootstrap.ts, bricks/visual-builder/src/workbench-action-list/example.yaml, bricks/visual-builder/src/workbench-action-list/index.spec.tsx, bricks/visual-builder/src/workbench-action-list/index.tsx, bricks/visual-builder/src/workbench-action-list/workbench-action-list.shadow.css, bricks/visual-builder/src/workbench-action/example.yaml, bricks/visual-builder/src/workbench-action/index.spec.ts, bricks/visual-builder/src/workbench-action/index.tsx, bricks/visual-builder/src/workbench-action/workbench-action.shadow.css, declarations/global.d.ts, shared/general/package.json
Refs NEXT_BUILDER-3149
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support workbench-aciton-list

bricks/data-view/src/cabinet/index.spec.ts, bricks/data-view/src/cabinet/index.tsx
refs DASHBOARD-409
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(cabinet): activeKey support array

bricks/basic/src/tag/index.tsx
=> fix(): tag removed error

bricks/v2-adapter/src/data-providers/legacy-brick-kit/LegacyUseBrick.tsx
=> fix(): fix v2 useBrick missing refCallback

bricks/data-view/src/modern-style-treemap/index.spec.tsx, bricks/data-view/src/modern-style-treemap/index.tsx
refs DASHBOARD-417
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): treemap support click event

bricks/markdown/package.json
=> chore(): update markdown-NB version

bricks/data-view/src/cabinet/index.spec.ts, bricks/data-view/src/cabinet/index.tsx
refs DASHBOARD-422
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): cabinet support  hiddenCloseBtn property

bricks/icons/src/fa-icon/index.spec.ts, bricks/icons/src/fa-icon/index.tsx
=> fix(fa-icon): cache for fetching icons

bricks/containers/src/bootstrap.ts, bricks/containers/src/easy-view/easy-view.shadow.css, bricks/containers/src/easy-view/example.html, bricks/containers/src/easy-view/index.spec.ts, bricks/containers/src/easy-view/index.tsx
=> feat(): support easy-view in v3

bricks/data-view/src/complex-search/index.tsx
refs BLKSH-128
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): 搜索框无法清除值

bricks/basic/src/dropdown-button/dropdown-button.shadow.css, bricks/basic/src/dropdown-button/index.spec.ts, bricks/basic/src/dropdown-button/index.tsx, bricks/basic/src/menu-item/index.spec.ts, bricks/basic/src/menu-item/index.tsx, bricks/basic/src/menu-item/menuItem.shadow.css, bricks/basic/src/popover/index.spec.ts, bricks/basic/src/popover/index.spec.tsx, bricks/basic/src/popover/index.tsx, bricks/basic/src/popover/popover.shadow.css, bricks/basic/src/popover/popup.ts
=> feat(): add animate in popover brick

bricks/advanced/package.json, bricks/basic/package.json, bricks/containers/package.json, bricks/data-view/package.json, bricks/devtools/package.json, bricks/form/package.json, bricks/icons/package.json, bricks/illustrations/package.json, bricks/markdown/package.json, bricks/presentational/package.json, bricks/shoelace/package.json, bricks/v2-adapter/package.json, bricks/visual-builder/package.json, yarn.lock
=> chore(): build:manifest

.github/workflows/docs.yml, CONTRIBUTING.md, README.md
=> chore(ci): preview docs

bricks/visual-builder/src/workbench-pane/index.tsx, bricks/visual-builder/src/workbench-sidebar/example.yaml, bricks/visual-builder/src/workbench-sidebar/index.spec.ts, bricks/visual-builder/src/workbench-sidebar/index.tsx
=> fix(): slot name modify

package.json, yarn.lock
=> chore(): yo: help to create bricks

bricks/data-view/src/cabinet/cabinet-container/cabinet-container.shadow.css, bricks/data-view/src/cabinet/cabinet-container/index.spec.ts, bricks/data-view/src/cabinet/cabinet-container/index.tsx, bricks/data-view/src/cabinet/cabinet.shadow.css, bricks/data-view/src/cabinet/index.spec.ts, bricks/data-view/src/cabinet/index.tsx
Closes DASHBOARD-438
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(data-view): cabinet某些临界值未考虑

bricks/basic/docs/dropdown-button.md, bricks/basic/docs/general-image.md, bricks/basic/docs/general-tag-list.md, bricks/basic/docs/general-tag.md, bricks/basic/docs/general-text.md, bricks/basic/src/button/button.shadow.css, bricks/basic/src/button/index.spec.ts, bricks/basic/src/button/index.tsx, bricks/basic/src/dropdown-button/index.tsx, bricks/basic/src/image/index.tsx, bricks/basic/src/link/index.tsx, bricks/basic/src/link/link.shadow.css, bricks/basic/src/tag-list/index.tsx, bricks/basic/src/tag/index.tsx, bricks/basic/src/text/index.tsx
=> feat(): update basic docs

bricks/presentational/docs/general-descriptions.md, bricks/presentational/src/descriptions/index.tsx
=> chore(): update presentiontal docs

bricks/containers/docs/easy-view.md, bricks/containers/docs/flex-layout.md, bricks/containers/docs/general-card.md, bricks/containers/docs/general-category.md, bricks/containers/docs/general-drawer.md, bricks/containers/docs/general-modal.md, bricks/containers/docs/grid-layout.md, bricks/containers/docs/micro-view.md, bricks/containers/docs/tab-list.md, bricks/containers/src/card/index.tsx, bricks/containers/src/category/index.tsx, bricks/containers/src/drawer/index.tsx, bricks/containers/src/easy-view/index.tsx, bricks/containers/src/flex-layout/index.tsx, bricks/containers/src/grid-layout/index.tsx, bricks/containers/src/micro-view/index.tsx, bricks/containers/src/modal/index.tsx, bricks/containers/src/tab/tab-list/index.tsx, bricks/form/src/input/index.tsx
=> chore(): support container docs

bricks/icons/package.json, bricks/icons/scripts/pre-build.js, bricks/icons/src/bootstrap.ts, bricks/icons/src/data-providers/get-icons.ts, bricks/icons/src/data-providers/get-libs.spec.ts, bricks/icons/src/data-providers/get-libs.ts, bricks/icons/src/data-providers/search-icons.spec.ts, bricks/icons/src/data-providers/search-icons.ts, bricks/icons/src/fa-icon/index.tsx
Closes NEXT_BUILDER-3361
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support icons.get-libs & icons.search-icons

bricks/visual-builder/package.json, bricks/visual-builder/src/bootstrap.ts, bricks/visual-builder/src/interfaces.ts, bricks/visual-builder/src/shared/workbench-mini-action-bar/WorkbenchMiniActionBar.shadow.css, bricks/visual-builder/src/shared/workbench-mini-action-bar/WorkbenchMiniActionBar.spec.tsx, bricks/visual-builder/src/shared/workbench-mini-action-bar/WorkbenchMiniActionBar.tsx, bricks/visual-builder/src/shared/workbench/WorkbenchActionsContext.ts, bricks/visual-builder/src/shared/workbench/WorkbenchTree.spec.tsx, bricks/visual-builder/src/shared/workbench/WorkbenchTree.tsx, bricks/visual-builder/src/shared/workbench/WorkbenchTreeContext.ts, bricks/visual-builder/src/shared/workbench/WorkbenchTreeDndContext.ts, bricks/visual-builder/src/utils/deepMatch.spec.ts, bricks/visual-builder/src/utils/deepMatch.ts, bricks/visual-builder/src/utils/normalizeTreeNodeWithPath.spec.ts, bricks/visual-builder/src/utils/normalizeTreeNodeWithPath.ts, bricks/visual-builder/src/utils/setDragImage.ts, bricks/visual-builder/src/workbench-tree/WorkbenchTree.shadow.css, bricks/visual-builder/src/workbench-tree/index.spec.ts, bricks/visual-builder/src/workbench-tree/index.tsx
=> feat(): support workbench tree in v3

bricks/form/docs/general-search.md, bricks/form/src/bootstrap.ts, bricks/form/src/search/index.spec.tsx, bricks/form/src/search/index.tsx, bricks/form/src/search/styles.shadow.css
Closes NEXT_BUILDER-3380
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): general-search构件

bricks/advanced/docs/general-table.md, bricks/advanced/src/table/index.tsx, bricks/basic/docs/general-tag-list.md
=> chore(): support advanced docs

bricks/data-view/src/app-wall/app-wall.tsx
refs BRICK-12
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 修复应用墙hover双击效果不对的问题

bricks/containers/src/modal/index.tsx, bricks/form/docs/icon-select.md, bricks/form/src/bootstrap.ts, bricks/form/src/icon-select/i18n.ts, bricks/form/src/icon-select/index.spec.tsx, bricks/form/src/icon-select/index.tsx, bricks/form/src/icon-select/styles.shadow.css, bricks/form/src/icon-select/utils.ts, bricks/form/src/radio/index.tsx, bricks/form/src/search/index.tsx
Closes NEXT_BUILDER-3238
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): icon-select构件

bricks/data-view/src/tabs-drawer/index.spec.tsx, bricks/data-view/src/tabs-drawer/index.tsx
Closes DASHBOARD-452
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): tabs-drawer点击非自身元素收起

bricks/basic/deploy/package.conf.yaml, bricks/basic/package.json
=> chore(): update dependencies

bricks/basic/package.json, bricks/basic/src/data-providers/show-dialog/dialog.module.css, bricks/basic/src/data-providers/show-dialog/example.yaml, bricks/basic/src/data-providers/show-dialog/i18n.ts, bricks/basic/src/data-providers/show-dialog/show-dialog.spec.tsx, bricks/basic/src/data-providers/show-dialog/show-dialog.tsx, bricks/form/src/form-item/index.tsx, bricks/form/src/input/input.shadow.css
Closes NEXT_BUILDER-3248
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): show-dialog 支持 delete 类型

bricks/form/docs/upload-image.md, bricks/form/src/bootstrap.ts, bricks/form/src/upload/Upload.spec.tsx, bricks/form/src/upload/Upload.tsx, bricks/form/src/upload/upload-image/i18n.ts, bricks/form/src/upload/upload-image/index.spec.tsx, bricks/form/src/upload/upload-image/index.tsx, bricks/form/src/upload/upload-image/styles.shadow.css, bricks/form/src/upload/utils.ts
Closes NEXT_BUILDER-3362
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): upload-image

bricks/data-view/src/tabs-drawer/index.spec.tsx, bricks/data-view/src/tabs-drawer/index.tsx
Closes DASHBOARD-452
请勾选以下两组选项其中之一：
或者：
>
>
=> fix():优化构件

bricks/form/docs/general-switch.md, bricks/form/src/bootstrap.ts, bricks/form/src/general-switch/index.spec.tsx, bricks/form/src/general-switch/index.tsx, bricks/form/src/general-switch/styles.shadow.css
Closes NEXT_BUILDER-3240
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): general-switch

bricks/basic/src/data-providers/show-dialog/dialog.module.css, bricks/basic/src/data-providers/show-dialog/example.yaml, bricks/basic/src/data-providers/show-dialog/show-dialog.spec.tsx, bricks/basic/src/data-providers/show-dialog/show-dialog.tsx
Closes NEXT_BUILDER-3444
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): show-dialog support highlight expect

bricks/basic/src/bootstrap.ts, bricks/basic/src/data-providers/copy-to-clipboard.spec.ts, bricks/basic/src/data-providers/copy-to-clipboard.ts, bricks/basic/src/data-providers/copy-to-clipboard/example.yaml
Closes NEXT_BUILDER-3478
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): basic.copy-to-clipboard

bricks/basic/src/button/index.tsx, bricks/basic/src/launchpad/LaunchpadButton/LaunchpadButton.spec.tsx, bricks/basic/src/launchpad/LaunchpadService.spec.ts, bricks/basic/src/launchpad/MyDesktop/MyDesktop.spec.tsx, bricks/basic/src/launchpad/SearchBar/SearchBar.spec.tsx, bricks/basic/src/launchpad/SearchBar/SearchBar.tsx, bricks/basic/src/link/getExtendedLocationDescriptor.ts, bricks/basic/src/link/index.spec.tsx, bricks/basic/src/link/index.tsx, bricks/basic/src/nav-menu/index.spec.ts, bricks/basic/src/nav-menu/index.tsx, bricks/basic/src/nav-menu/utils.tsx, jest/__mocks__/react-i18next.js
=> feat(): link url support location descriptor

bricks/data-view/src/graph/text/index.spec.ts
=> fix(): i18n unit test

bricks/presentational/docs/general-alert.md, bricks/presentational/package.json, bricks/presentational/src/bootstrap.ts, bricks/presentational/src/general-alert/constants.ts, bricks/presentational/src/general-alert/index.spec.tsx, bricks/presentational/src/general-alert/index.tsx, bricks/presentational/src/general-alert/styles.shadow.css
Closes NEXT_BUILDER-3246
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): 告警提示构件

bricks/advanced/deploy-default/package.conf.yaml, bricks/containers/deploy-default/package.conf.yaml, bricks/data-view/deploy-default/package.conf.yaml, bricks/form/deploy-default/package.conf.yaml, bricks/presentational/deploy-default/package.conf.yaml, bricks/visual-builder/deploy-default/package.conf.yaml, bricks/vs/deploy-default/package.conf.yaml
=> fix(): refine artifact deps

bricks/basic/src/link/index.tsx
=> fix(): fix link error in shadow dom

bricks/form/src/upload/Upload.spec.tsx, bricks/form/src/upload/Upload.tsx, bricks/form/src/upload/upload-image/index.spec.tsx, bricks/form/src/upload/upload-image/index.tsx, bricks/form/src/upload/upload-image/styles.shadow.css, bricks/form/src/upload/upload-image/utils.spec.ts, bricks/form/src/upload/upload-image/utils.ts, bricks/form/src/upload/utils.spec.ts, bricks/form/src/upload/utils.ts
Closes NEXT_BUILDER-3482
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): style update && update data structure

bricks/data-view/docs/title-text.md, bricks/data-view/src/bootstrap.ts, bricks/data-view/src/title-text/index.spec.tsx, bricks/data-view/src/title-text/index.tsx, bricks/data-view/src/title-text/styles.shadow.css
Closes MONITOR-6423
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view):support title-text component

bricks/v2-adapter/src/data-providers/legacy-brick-kit/LegacyUseBrick.tsx
=> fix(): handle useBrick ignored

bricks/data-view/docs/brick-notification.md, bricks/data-view/src/bootstrap.ts, bricks/data-view/src/brick-notification/index.spec.ts, bricks/data-view/src/brick-notification/index.tsx, bricks/data-view/src/brick-notification/styles.shadow.css, bricks/data-view/src/title-text/index.tsx
Closes MONITOR-6424
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view):support brick-notification component

bricks/basic/src/dropdown-button/index.spec.ts, bricks/basic/src/dropdown-button/index.tsx, bricks/form/src/radio/index.tsx, bricks/form/src/upload/upload-image/styles.shadow.css
Closes NEXT_BUILDER-3494
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): 构件样式调整 & dropdown actions 支持 hidden

bricks/basic/src/dropdown-button/index.spec.ts, bricks/basic/src/dropdown-button/index.tsx, bricks/basic/src/menu/menu.shadow.css, bricks/basic/src/popover/index.spec.tsx, bricks/basic/src/popover/index.tsx, bricks/basic/src/popover/popup.ts
Closes NEXT_BUILDER-3206
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): keep popup in view && default distance && dropdown sync width

bricks/data-view/docs/tabs-page-title.md, bricks/data-view/src/bootstrap.ts, bricks/data-view/src/tabs-page-title/index.spec.tsx, bricks/data-view/src/tabs-page-title/index.tsx, bricks/data-view/src/tabs-page-title/styles.shadow.css, bricks/data-view/src/title-text/index.spec.tsx, bricks/data-view/src/title-text/index.tsx, bricks/data-view/src/title-text/styles.shadow.css
Closes MONITOR-6425 MONITOR-6426
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): support tabs-page-title component

bricks/data-view/docs/top-title-bar.md, bricks/data-view/src/bootstrap.ts, bricks/data-view/src/top-title-bar/index.spec.tsx, bricks/data-view/src/top-title-bar/index.tsx, bricks/data-view/src/top-title-bar/styles.shadow.css
=> feat():新增数据大标题栏  Closes MONITOR-6439

bricks/data-view/docs/lights-component-title.md, bricks/data-view/src/bootstrap.ts, bricks/data-view/src/lights-component-title/index.spec.tsx, bricks/data-view/src/lights-component-title/index.tsx, bricks/data-view/src/lights-component-title/styles.shadow.css
Closes MONITOR-6450
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): support new-style-component-title component

bricks/v2-adapter/src/data-providers/load-bricks.tsx
=> fix(): fix typo: `ea-` => `eo-`

babel.config.js, bricks/presentational/.babelrc.cjs, bricks/presentational/package.json, bricks/presentational/src/code-display/index.spec.tsx, bricks/presentational/src/code-display/index.tsx, bricks/presentational/src/code-display/styles.shadow.css, bricks/presentational/src/code-display/themes/tomorrow.ts, bricks/presentational/src/code-display/utils.ts, yarn.lock
Closes NEXT_BUILDER-3243
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): use prism-react-renderer && support dynamic import language

bricks/v2-adapter/src/data-providers/legacy-brick-kit/LegacyUseBrick.tsx
=> fix(useBrick): do not call ignoredCallback at initial

bricks/markdown/build.config.js, bricks/markdown/package.json, bricks/markdown/src/markdown-editor/components/TableWidget.tsx, bricks/markdown/src/markdown-editor/index.tsx, bricks/markdown/src/markdown-editor/markdown-editor.shadow.css, yarn.lock
Ref: POKEMON-560
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): v3 markdown构件table支持tooltip显示操作选项

bricks/presentational/docs/eo-pagination.md, bricks/presentational/src/bootstrap.ts, bricks/presentational/src/pagination/i18n.ts, bricks/presentational/src/pagination/index.spec.tsx, bricks/presentational/src/pagination/index.tsx, bricks/presentational/src/pagination/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3572
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-pagination

bricks/data-view/docs/lights-component-title.md, bricks/data-view/src/asset/images/darkBg.svg, bricks/data-view/src/asset/images/darkIcon.svg, bricks/data-view/src/asset/images/lightBg.svg, bricks/data-view/src/asset/images/lightIcon.svg, bricks/data-view/src/lights-component-title/index.spec.tsx, bricks/data-view/src/lights-component-title/index.tsx, bricks/data-view/src/lights-component-title/styles.shadow.css
Refs MONITOR-6449
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): 标题构件增加dark样式

bricks/recent-history/build.config.js, bricks/recent-history/docs/recent-visit.md, bricks/recent-history/package.json, bricks/recent-history/src/bootstrap.ts, bricks/recent-history/src/data-providers/visit-history.spec.ts, bricks/recent-history/src/data-providers/visit-history.ts, bricks/recent-history/src/index.ts, bricks/recent-history/src/recent-visit/i18n.ts, bricks/recent-history/src/recent-visit/index.spec.tsx, bricks/recent-history/src/recent-visit/index.tsx, bricks/recent-history/src/recent-visit/styles.shadow.css, bricks/recent-history/src/utils.ts, bricks/recent-history/tsconfig.json, yarn.lock
Closes NEXT_BUILDER-3570
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): visit-history

bricks/containers/docs/eo-spin.md, bricks/containers/src/bootstrap.ts, bricks/containers/src/spin/index.spec.tsx, bricks/containers/src/spin/index.tsx, bricks/containers/src/spin/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3573
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-spin

bricks/basic/docs/eo-link.md, bricks/basic/src/interface.ts, bricks/basic/src/link/link.shadow.css
Closes NEXT_BUILDER-3571
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): link support plain type

bricks/markdown/src/markdown-editor/index.tsx
=> fix(): markdown track value

bricks/basic/docs/eo-mini-actions.md, bricks/basic/src/bootstrap.ts, bricks/basic/src/mini-actions/index.spec.tsx, bricks/basic/src/mini-actions/index.tsx, bricks/basic/src/mini-actions/styles.shadow.css, bricks/basic/src/popover/index.tsx, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3571
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-small-button-group

bricks/basic/src/mini-actions/index.tsx, bricks/presentational/docs/eo-card-item.md, bricks/presentational/src/bootstrap.ts, bricks/presentational/src/card-item/index.spec.tsx, bricks/presentational/src/card-item/index.tsx, bricks/presentational/src/card-item/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3571
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-card-item

bricks/vs/docs/code-editor.md, bricks/vs/package.json, bricks/vs/src/code-editor/index.tsx, bricks/vs/src/code-editor/utils/brickNextSourceMap.ts, bricks/vs/src/code-editor/utils/brickNextYaml.ts, bricks/vs/src/code-editor/utils/constants.ts
=> feat(): monaco editor support parse yaml&highlight

bricks/markdown/src/markdown-editor/index.tsx, bricks/markdown/src/markdown-editor/markdown-editor.shadow.css
=> fix(): update styles to be compatible with the dark mode

bricks/markdown/src/markdown-editor/markdown-editor.shadow.css
=> fix(): update markdown styles

bricks/form/docs/eo-upload-file.md, bricks/form/src/bootstrap.ts, bricks/form/src/upload/Upload.spec.tsx, bricks/form/src/upload/Upload.tsx, bricks/form/src/upload/upload-file/i18n.ts, bricks/form/src/upload/upload-file/index.spec.tsx, bricks/form/src/upload/upload-file/index.tsx, bricks/form/src/upload/upload-file/styles.shadow.css, bricks/form/src/upload/upload-image/index.tsx, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3569
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-upload-file

bricks/form/src/search/index.tsx, bricks/presentational/src/pagination/index.spec.tsx, bricks/presentational/src/pagination/index.tsx
Closes NEXT_BUILDER-3574
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): pagination property is not updated when it changes

bricks/basic/docs/eo-link.md, bricks/basic/src/button/button.shadow.css, bricks/basic/src/link/link.shadow.css, bricks/basic/src/menu-item/menuItem.shadow.css, bricks/basic/src/popover/index.spec.tsx, bricks/basic/src/popover/index.tsx, bricks/basic/src/tag/tag.shadow.css, bricks/containers/src/tab/tab-item/tab-item.shadow.css, bricks/form/docs/eo-form.md, bricks/form/src/checkbox/index.spec.tsx, bricks/form/src/form-item/FormItem.shadow.css, bricks/form/src/form-item/index.tsx, bricks/form/src/form/index.spec.tsx, bricks/form/src/form/index.tsx, bricks/form/src/utils/formatOptions.spec.ts, bricks/vs/src/code-editor/index.tsx
=> fix(): fix style

bricks/basic/src/nav-menu/nav-menu.shadow.css
=> fix(): nav style

bricks/form/src/icon-select/index.tsx, bricks/form/src/icon-select/styles.shadow.css, bricks/form/src/radio/index.tsx
=> fix(): icon-select style

bricks/form/src/checkbox/index.tsx, bricks/form/src/dynamic-form-item/index.tsx, bricks/form/src/form-item/FormItem.shadow.css, bricks/form/src/form-item/index.tsx, bricks/form/src/general-switch/index.tsx, bricks/form/src/icon-select/index.tsx, bricks/form/src/input/index.tsx, bricks/form/src/radio/index.tsx, bricks/form/src/select/index.tsx, bricks/form/src/textarea/index.tsx, bricks/form/src/upload/upload-file/index.tsx, bricks/form/src/upload/upload-image/index.tsx, shared/form/src/FormItemElement.tsx, shared/form/src/FormStore.ts
=> feat(): formItem support setNotRender & helpBrick

bricks/advanced/package.json, bricks/basic/package.json, bricks/data-view/package.json, bricks/form/package.json, bricks/presentational/package.json, bricks/vs/package.json, yarn.lock
=> fix(): now supports v3 bricks with useBrick used in v2

bricks/v2-adapter/src/data-providers/legacy-brick-kit/getLegacyRuntime.ts
Closes NEXT_BUILDER-3688
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): runtime export hasInstalledApp

bricks/v2-adapter/src/data-providers/load-bricks.tsx
Closes NEXT_BUILDER-3690
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): FontAwesomeIcon do not work well

bricks/markdown/src/markdown-editor/markdown-editor.shadow.css
=> v3 markdown构件 优化link交互，暗色模式下不方便编辑

bricks/vb-experiment/build.config.js, bricks/vb-experiment/package.json, bricks/vb-experiment/src/bootstrap.ts, bricks/vb-experiment/src/data-providers/export-as-source-files.spec.ts, bricks/vb-experiment/src/data-providers/export-as-source-files.ts, bricks/vb-experiment/src/index.ts, bricks/vb-experiment/tsconfig.json, yarn.lock
=> feat(): export as source files

bricks/form/src/form-item/index.tsx, shared/form/src/FormItemElement.tsx
Closes NEXT_BUILDER-3577
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): form-item support labelBrick

bricks/form/docs/eo-input.md, bricks/form/src/input/index.spec.tsx, bricks/form/src/input/index.tsx, bricks/form/src/input/input.shadow.css, bricks/icons/src/general-icon/styles.shadow.css
Closes NEXT_BUILDER-3578
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): input support addon && refactor

bricks/form/src/form-item/index.tsx, bricks/form/src/icon-select/index.spec.tsx, bricks/form/src/icon-select/index.tsx, bricks/form/src/icon-select/styles.shadow.css, bricks/form/src/input/index.tsx, bricks/form/src/input/input.shadow.css, bricks/form/src/search/index.spec.tsx, bricks/form/src/search/index.tsx, bricks/form/src/search/styles.shadow.css
Closes NEXT_BUILDER-3578
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-input support autoFocus && refactor eo-search

bricks/vb-experiment/src/data-providers/export-as-source-files.ts, bricks/vb-experiment/src/data-providers/utils/buildFileStructure.ts, bricks/vb-experiment/src/data-providers/utils/extract.ts, bricks/vb-experiment/src/data-providers/utils/printWithPlaceholders.ts
=> fix(): extract source files

bricks/basic/docs/eo-tooltip.md, bricks/basic/src/bootstrap.ts, bricks/basic/src/tooltip/index.spec.tsx, bricks/basic/src/tooltip/index.tsx, bricks/basic/src/tooltip/sl-tooltip.ts, bricks/basic/src/tooltip/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3576
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-tooltip

bricks/markdown/src/markdown-editor/index.tsx
=> feat(): refactor markdown as a form-component

bricks/markdown/src/markdown-editor/index.tsx
Reverts easyops-cn/next-bricks#327
=> Revert "feat(): refactor markdown as a form-component"

bricks/vb-experiment/src/data-providers/export-as-source-files.ts
=> fix(): add dev.config.mjs

bricks/data-view/src/cabinet/cabinet-thumbnail/index.spec.tsx, bricks/data-view/src/cabinet/cabinet-thumbnail/index.tsx
refs CUSTOMIZE-340
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(cabinet-thumbnail): 调整适配scale比例

bricks/markdown/src/markdown-editor/index.tsx
=> feat(): refactor markdown editor as a form component

bricks/basic/src/tooltip/index.spec.tsx, bricks/basic/src/tooltip/index.tsx
Closes NEXT_BUILDER-3754
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): don't show tooltip when content is empty

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/index.tsx, bricks/data-view/src/app-wall/utils.ts
refs CUSTOMIZE-341
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(app-wall): 新增useDistanceConfig属性是否使用内置的distanceConfig配置

bricks/markdown/src/markdown-editor/index.tsx
=> feat(): support form method setInitValue and resrtFields

bricks/visual-builder/package.json, bricks/visual-builder/src/bootstrap.ts, bricks/visual-builder/src/data-providers/collect-used-contracts.spec.ts, bricks/visual-builder/src/data-providers/collect-used-contracts.ts, bricks/visual-builder/src/data-providers/preview/connect.ts, yarn.lock
Refs NEXT_BUILDER-3752
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): v3 support auto build & push in preivew

bricks/basic/src/link/index.tsx, bricks/basic/src/menu-item/index.tsx, bricks/form/src/input/index.tsx
=> chore(): doc for part

bricks/basic/docs/eo-dropdown-actions.md, bricks/basic/docs/eo-popover.md, bricks/basic/src/bootstrap.ts, bricks/basic/src/dropdown-actions/index.spec.tsx, bricks/basic/src/dropdown-actions/index.tsx, bricks/basic/src/dropdown-actions/styles.shadow.css, bricks/basic/src/dropdown-button/dropdown-button.shadow.css, bricks/basic/src/dropdown-button/index.spec.ts, bricks/basic/src/dropdown-button/index.tsx, bricks/basic/src/menu-item/menuItem.shadow.css, bricks/basic/src/popover/index.spec.tsx, bricks/basic/src/popover/index.tsx, bricks/basic/src/tooltip/index.tsx, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3797
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-dropdown-actions

bricks/basic/docs/eo-avatar.md, bricks/basic/src/avatar/index.spec.tsx, bricks/basic/src/avatar/index.tsx, bricks/basic/src/avatar/styles.shadow.css, bricks/basic/src/bootstrap.ts, bricks/basic/src/dropdown-actions/styles.shadow.css, bricks/basic/src/link/link.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3797
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-avatar

bricks/presentational/docs/eo-divider.md, bricks/presentational/src/bootstrap.ts, bricks/presentational/src/divider/index.spec.tsx, bricks/presentational/src/divider/index.tsx, bricks/presentational/src/divider/styles.shadow.css, shared/common-bricks/common-bricks.json
=> feat(): support eo-divider ref NEXT_BUILDER-3786

bricks/basic/src/menu-item/index.spec.ts, bricks/basic/src/menu-item/index.tsx, bricks/basic/src/menu-item/menuItem.shadow.css, bricks/basic/src/sidebar-sub-menu/index.tsx, bricks/basic/src/sidebar-sub-menu/styles.shadow.css
Refs NEXT_BUILDER-3795
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): restore menu-item previous state

bricks/form/docs/eo-dynamic-form-item.md, bricks/form/src/dynamic-form-item/dynamic-form-item.shadow.css, bricks/form/src/dynamic-form-item/i18n.ts, bricks/form/src/dynamic-form-item/index.spec.tsx, bricks/form/src/dynamic-form-item/index.tsx, bricks/form/src/input/index.tsx, shared/form/src/FormStore.ts
Closes NEXT_BUILDER-3804
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-dynamic-form-item

bricks/vb-experiment/build.config.js, bricks/vb-experiment/src/data-providers/export-as-source-files.ts, bricks/vb-experiment/src/data-providers/raws/jsx/jsx-runtime.js.txt, bricks/vb-experiment/src/data-providers/raws/package.json.txt, bricks/vb-experiment/src/data-providers/raws/scripts/build.js.txt, bricks/vb-experiment/src/data-providers/raws/src/resources/index.js.txt, bricks/vb-experiment/src/data-providers/utils/extract.ts, bricks/vb-experiment/src/data-providers/utils/printWithPlaceholders.ts
=> fix(): refine exporting: fix non-ascii attributes, extract contacts, etc.

bricks/basic/docs/eo-breadcrumb-item.md, bricks/basic/docs/eo-breadcrumb.md, bricks/basic/docs/eo-frame-breadcrumb.md, bricks/basic/src/bootstrap.ts, bricks/basic/src/breadcrumb-item/index.spec.tsx, bricks/basic/src/breadcrumb-item/index.tsx, bricks/basic/src/breadcrumb-item/styles.shadow.css, bricks/basic/src/breadcrumb/index.spec.tsx, bricks/basic/src/breadcrumb/index.tsx, bricks/basic/src/breadcrumb/styles.shadow.css, bricks/basic/src/frame-breadcrumb/index.spec.tsx, bricks/basic/src/frame-breadcrumb/index.tsx, bricks/basic/src/frame-breadcrumb/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3798
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-breadcrumb

bricks/basic/docs/eo-sidebar-menu-group.md, bricks/basic/docs/eo-sidebar-menu-item.md, bricks/basic/docs/eo-sidebar-menu-submenu.md, bricks/basic/docs/eo-sidebar-menu.md, bricks/basic/src/bootstrap.ts, bricks/basic/src/sidebar/sidebar-menu-group/index.spec.tsx, bricks/basic/src/sidebar/sidebar-menu-group/index.tsx, bricks/basic/src/sidebar/sidebar-menu-group/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-item/index.spec.tsx, bricks/basic/src/sidebar/sidebar-menu-item/index.tsx, bricks/basic/src/sidebar/sidebar-menu-item/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-submenu/index.spec.tsx, bricks/basic/src/sidebar/sidebar-menu-submenu/index.tsx, bricks/basic/src/sidebar/sidebar-menu-submenu/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu/index.spec.tsx, bricks/basic/src/sidebar/sidebar-menu/index.tsx, bricks/basic/src/sidebar/sidebar-menu/styles.shadow.css, bricks/basic/src/sidebar/utils.ts, bricks/basic/src/sidebar/utils.tsx, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3794
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-sidebar-menu

bricks/presentational/docs/eo-info-card-item.md, bricks/presentational/src/bootstrap.ts, bricks/presentational/src/info-card-item/index.spec.tsx, bricks/presentational/src/info-card-item/index.tsx, bricks/presentational/src/info-card-item/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-3776
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): presentational-bricks.info-display-card-list

bricks/basic/src/button/button.shadow.css, bricks/basic/src/button/index.tsx, bricks/containers/src/grid-layout/index.tsx, bricks/presentational/src/card-item/styles.shadow.css, bricks/presentational/src/info-card-item/styles.shadow.css
Ref  NEXT_BUILDER-3820
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): some css fix

bricks/basic/docs/eo-dropdown-actions.md, bricks/basic/src/dropdown-actions/index.spec.tsx, bricks/basic/src/dropdown-actions/index.tsx, bricks/basic/src/dropdown-actions/styles.shadow.css, bricks/basic/src/dropdown-button/index.tsx, bricks/containers/docs/eo-drawer.md, bricks/containers/src/drawer/drawer.shadow.css, bricks/containers/src/drawer/index.tsx
=> feat(): eo-dropdown-actions support divider and danger action

bricks/basic/src/app-bar-wrapper/styles.shadow.css
=> chore(): style fix

bricks/basic/docs/eo-page-title.md, bricks/basic/src/bootstrap.ts, bricks/basic/src/nav-menu/nav-menu.shadow.css, bricks/basic/src/page-title/index.spec.tsx, bricks/basic/src/page-title/index.tsx, bricks/basic/src/page-title/styles.shadow.css, shared/common-bricks/common-bricks.json
=> feat(): support eo-page-title ref NEXT_BUILDER-3786

bricks/basic/src/nav-menu/index.tsx
=> fix(): fix eo-nav-bar bug ref NEXT_BUILDER-3786

bricks/presentational/docs/eo-counter-badge.md, bricks/presentational/src/counter-badge/index.tsx, bricks/presentational/src/counter-badge/styles.shadow.css
Refs NEXT_BUILDER-3820
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(counter-badge): support no content style

bricks/vb-experiment/src/data-providers/raws/README.md.txt, bricks/vb-experiment/src/data-providers/raws/dev.config.mjs.txt, bricks/vb-experiment/src/data-providers/raws/package.json.txt, bricks/vb-experiment/src/data-providers/utils/extract.ts
=> fix(): throw when brick.properties is string

bricks/containers/docs/eo-tab-list.md, bricks/containers/src/tab/tab-group/tab.shadow.css, bricks/containers/src/tab/tab-item/index.tsx, bricks/containers/src/tab/tab-item/tab-item.shadow.css
=> feat(tab-item): add badgeConf property

bricks/basic/src/counter-badge/index.spec.tsx, bricks/basic/src/counter-badge/index.tsx
=> fix(counter-badge): fix icon only style

bricks/basic/src/dropdown-actions/index.tsx, bricks/basic/src/mini-actions/index.tsx
Closes NEXT_BUILDER-3885
Closes NEXT_BUILDER-3845
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): eo-dropdown-actions、eo-mini-actions暂停使用eo-popover的sync属性

bricks/vb-experiment/src/data-providers/export-as-source-files.ts, bricks/vb-experiment/src/data-providers/raws/declarations.d.ts.txt, bricks/vb-experiment/src/data-providers/raws/jsconfig.json.txt, bricks/vb-experiment/src/data-providers/raws/package.json.txt
=> fix(): refine FN auto-import

bricks/containers/src/search-bar/index.tsx
Refs NEXT_BUILDER-3743
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 补充marginBottom

bricks/basic/src/avatar/styles.shadow.css
=> fix(): avatar is not aligned

bricks/basic/src/dropdown-actions/styles.shadow.css, bricks/basic/src/launchpad/LaunchpadButton/LaunchpadButton.shadow.css, bricks/basic/src/sidebar-sub-menu/index.tsx, bricks/basic/src/sidebar-sub-menu/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-group/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-item/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-submenu/styles.shadow.css, bricks/basic/src/sidebar/styles.shadow.css, bricks/containers/docs/eo-tab-list.md, bricks/containers/src/card/card.shadow.css, bricks/containers/src/tab/tab-group/index.tsx, bricks/containers/src/tab/tab-group/tab.shadow.css, bricks/containers/src/tab/tab-item/tab-item.shadow.css, bricks/containers/src/tab/tab-list/index.tsx, bricks/form/src/dynamic-form-item/dynamic-form-item.shadow.css, bricks/form/src/dynamic-form-item/index.tsx, bricks/form/src/input/input.shadow.css, bricks/form/src/select/index.shadow.css, bricks/form/src/textarea/textarea.shadow.css, bricks/presentational/src/pagination/styles.shadow.css
Closes NEXT_BUILDER-3838
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): 页面模板迭代一验收问题

.github/workflows/ci.yml, bricks/basic/docs/show-dialog.md, bricks/basic/docs/show-notification.md, bricks/illustrations/docs/get-illustration.md
=> docs(): fix docs

bricks/ui-test/src/data-providers/export-as-file.spec.ts, bricks/ui-test/src/data-providers/export-as-file.ts
Refs NEXT_BUILDER-3898
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): export to micro app directory

bricks/ui-test/src/bootstrap.ts, bricks/ui-test/src/data-providers/data/fetchCommands.ts, bricks/ui-test/src/data-providers/get-commands.spec.ts, bricks/ui-test/src/data-providers/get-commands.ts
=> feat(): get commands

bricks/ui-test/src/data-providers/get-commands.ts
=> fix(): fix filter

bricks/ui-test/src/custom-processors/get-tree-data.ts, bricks/ui-test/src/data-providers/export-as-file.ts, bricks/ui-test/src/utils/parseSuiteAst.spec.ts, bricks/ui-test/src/utils/parseSuiteAst.ts
Refs NEXT_BUILDER-3898
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): some optimization

bricks/ui-test/src/custom-processors/get-tree-data.spec.ts, bricks/ui-test/src/custom-processors/get-tree-data.ts, bricks/ui-test/src/data-providers/data/commands/custom.ts
=> fix(): refine tree node display labels

bricks/ui-test/package.json, bricks/ui-test/src/data-providers/data/commands/cypress/queries.ts, bricks/ui-test/src/data-providers/inject-preview-agent.ts, bricks/ui-test/src/data-providers/preview/inspector.ts, bricks/ui-test/src/data-providers/preview/interfaces.ts, bricks/ui-test/src/preview-container/InspectOutlineComponent.tsx, bricks/ui-test/src/preview-container/index.tsx, bricks/ui-test/src/preview-container/styles.shadow.css
=> feat(): support inspect

bricks/form-platform/build.config.js, bricks/form-platform/docs/eo-user-or-user-group-select.md, bricks/form-platform/package.json, bricks/form-platform/src/bootstrap.ts, bricks/form-platform/src/index.ts, bricks/form-platform/src/user-or-user-group-select/i18n.ts, bricks/form-platform/src/user-or-user-group-select/index.spec.tsx, bricks/form-platform/src/user-or-user-group-select/index.tsx, bricks/form-platform/src/user-or-user-group-select/styles.shadow.css, bricks/form-platform/tsconfig.json, bricks/form/src/interface.ts, bricks/form/src/select/index.shadow.css, bricks/form/src/select/index.spec.ts, bricks/form/src/select/index.tsx, bricks/form/src/utils/formatOptions.ts, shared/common-bricks/common-bricks.json
Closes BRICK-42
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): forms.user-or-user-group-select

bricks/visual-builder/src/data-providers/preview/connect.ts
=> fix(): sync route match after preview route change

bricks/ui-test/src/bootstrap.ts, bricks/ui-test/src/custom-processors/get-tree-data.spec.ts, bricks/ui-test/src/custom-processors/get-tree-data.ts, bricks/ui-test/src/data-providers/sort-test-tree-node.spec.ts, bricks/ui-test/src/data-providers/sort-test-tree-node.ts, bricks/ui-test/src/interface.ts
=> feat(): support sort

bricks/ui-test/src/preview-container/index.tsx
=> fix(): missing targetOrigin option

bricks/ui-test/src/data-providers/inject-preview-agent.ts, bricks/ui-test/src/data-providers/preview/inspector.ts, bricks/ui-test/src/data-providers/preview/interfaces.ts, bricks/ui-test/src/data-providers/preview/recorder.ts, bricks/ui-test/src/preview-container/index.tsx
=> feat(): support recording actions

bricks/ui-test/package.json, bricks/ui-test/src/bootstrap.ts, bricks/ui-test/src/custom-processors/get-tree-data.spec.ts, bricks/ui-test/src/custom-processors/get-tree-data.ts, bricks/ui-test/src/data-providers/clone-nodes.spec.ts, bricks/ui-test/src/data-providers/clone-nodes.ts, bricks/ui-test/src/interface.ts, yarn.lock
Refs NEXT_BUILDER-4010
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): test node support copy

bricks/ui-test/package.json, bricks/ui-test/src/bootstrap.ts, bricks/ui-test/src/data-providers/get-flat-nodes-in-tree.spec.ts, bricks/ui-test/src/data-providers/get-flat-nodes-in-tree.ts, bricks/ui-test/src/data-providers/preview/interfaces.ts, bricks/ui-test/src/data-providers/save-recorded-commands.spec.ts, bricks/ui-test/src/data-providers/save-recorded-commands.ts, bricks/ui-test/src/data-providers/shared/createNodes.spec.ts, bricks/ui-test/src/data-providers/shared/createNodes.ts, bricks/ui-test/src/interface.ts
=> feat(): save recorded commands

bricks/ui-test/src/custom-processors/get-tree-data.ts
=> fix(): sort node

bricks/ui-test/src/data-providers/data/commands/third-party.ts, bricks/ui-test/src/data-providers/export-as-file.spec.ts, bricks/ui-test/src/data-providers/get-commands.spec.ts
=> fix(): add `findByRole` and `findAll*`

bricks/vb-experiment/src/data-providers/raws/package.json.txt, bricks/vb-experiment/src/data-providers/utils/plugins/smart-imports.ts
=> fix(): add runtime variable: INDEX

bricks/form/docs/eo-auto-complete.md, bricks/form/src/auto-complete/index.spec.tsx, bricks/form/src/auto-complete/index.tsx, bricks/form/src/auto-complete/styles.shadow.css, bricks/form/src/bootstrap.ts, shared/common-bricks/common-bricks.json
=> feat():support eo-auto-complete ref BRICK-34

bricks/visual-builder/src/bootstrap.ts, bricks/visual-builder/src/data-providers/collect-used-contracts.ts, bricks/visual-builder/src/data-providers/inject-preview-agent.ts, bricks/visual-builder/src/data-providers/preview/connect.ts
=> fix(): pass collectUsedContracts as a function

bricks/basic/src/nav-menu/index.tsx, bricks/basic/src/nav-menu/nav-menu.shadow.css, bricks/basic/src/nav-menu/site-map/CollectService.spec.ts, bricks/basic/src/nav-menu/site-map/CollectService.ts, bricks/basic/src/nav-menu/site-map/GroupItem.shadow.css, bricks/basic/src/nav-menu/site-map/ItemTag.shadow.css, bricks/basic/src/nav-menu/site-map/ItemTag.spec.tsx, bricks/basic/src/nav-menu/site-map/ItemTag.tsx, bricks/basic/src/nav-menu/site-map/SiteMapItem.tsx, bricks/basic/src/nav-menu/site-map/constants.ts
…ll as well
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support drag

bricks/markdown/package.json, cypress/size-check.spec.js
=> fix(): add missing react-dom in dependencies

bricks/advanced/docs/eo-next-table.md, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/i18n.ts, bricks/advanced/src/next-table/index.spec.tsx, bricks/advanced/src/next-table/index.tsx, bricks/advanced/src/next-table/interface.ts, bricks/advanced/src/next-table/styles.shadow.css, bricks/advanced/src/next-table/utils.ts
Closes BRICK-78
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): next-table support useBrick & pagination

bricks/basic/src/nav-menu/site-map/GroupItem.shadow.css, bricks/basic/src/nav-menu/site-map/GroupItem.spec.tsx, bricks/basic/src/nav-menu/site-map/GroupItem.tsx, bricks/basic/src/nav-menu/site-map/SiteMapItem.tsx
=> fix(): menu active item

bricks/advanced/docs/eo-next-table.md, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/index.spec.tsx, bricks/advanced/src/next-table/index.tsx, bricks/advanced/src/next-table/utils.ts
Closes BRICK-78
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): next-table support hiddenColumns & front search

bricks/basic/src/nav-menu/nav-menu.shadow.css, bricks/basic/src/nav-menu/site-map/SiteMap.spec.tsx, bricks/basic/src/nav-menu/site-map/SiteMapItem.shadow.css, bricks/basic/src/nav-menu/site-map/SiteMapItem.tsx
=> fix(): refine style

bricks/ui-test/src/data-providers/inject-preview-agent.ts, bricks/ui-test/src/data-providers/preview/inspector.ts, bricks/ui-test/src/data-providers/preview/interfaces.ts, bricks/ui-test/src/preview-container/InspectOutlineComponent.tsx, bricks/ui-test/src/preview-container/index.tsx, bricks/ui-test/src/preview-container/styles.shadow.css
=> fix(): hover over tree node

bricks/advanced/deploy-default/package.conf.yaml, bricks/advanced/docs/eo-next-table.md, bricks/advanced/package.json, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/i18n.ts, bricks/advanced/src/next-table/index.spec.tsx, bricks/advanced/src/next-table/index.tsx, bricks/advanced/src/next-table/interface.ts, bricks/advanced/src/next-table/styles.shadow.css, bricks/advanced/src/next-table/utils.ts
Closes BRICK-85
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): next-table support rowSelection

bricks/advanced/package.json, bricks/basic/src/launchpad/DesktopSlider/DesktopSlider.tsx, bricks/form/docs/eo-time-picker.md, bricks/form/package.json, bricks/form/src/bootstrap.ts, bricks/form/src/time-picker/index.spec.tsx, bricks/form/src/time-picker/index.tsx, bricks/form/src/time-picker/styles.shadow.css, shared/common-bricks/common-bricks.json, yarn.lock
=> feat():support eo-time-picker ref BRICK-53

bricks/nav/src/nav-menu/nav-menu.shadow.css, bricks/nav/src/nav-menu/site-map/GroupItem.shadow.css, bricks/nav/src/nav-menu/site-map/GroupItem.tsx, bricks/nav/src/nav-menu/site-map/ItemTag.spec.tsx, bricks/nav/src/nav-menu/site-map/ItemTag.tsx, bricks/nav/src/nav-menu/site-map/SiteMapItem.shadow.css
=> fix(): add highlight background

bricks/ui-test/src/data-providers/preview/inspector.ts, bricks/ui-test/src/preview-container/styles.shadow.css
=> fix(): support find elements by `find`

bricks/advanced/src/next-table/i18n.ts
=> fix(): refine i18n locale types

bricks/nav/src/nav-menu/i18n.ts, bricks/nav/src/nav-menu/site-map/CollectService.spec.ts, bricks/nav/src/nav-menu/site-map/CollectService.ts, bricks/nav/src/nav-menu/site-map/GroupItem.tsx, bricks/nav/src/nav-menu/site-map/ItemTag.spec.tsx, bricks/nav/src/nav-menu/site-map/ItemTag.tsx, bricks/nav/src/nav-menu/site-map/SiteMap.spec.tsx
=> fix(): support max count tips

bricks/advanced/docs/eo-next-table.md, bricks/advanced/package.json, bricks/advanced/src/next-table/Row.tsx, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/index.spec.tsx, bricks/advanced/src/next-table/index.tsx, yarn.lock
Closes BRICK-84
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): next-table support rowDraggable

bricks/form/docs/eo-date-picker.md, bricks/form/src/bootstrap.ts, bricks/form/src/date-picker/i18n.ts, bricks/form/src/date-picker/index.spec.tsx, bricks/form/src/date-picker/index.tsx, bricks/form/src/date-picker/styles.shadow.css, bricks/form/src/interface.ts, bricks/form/src/time-picker/index.tsx, shared/common-bricks/common-bricks.json
=> feat():support eo-date-picker ref BRICK-53

bricks/advanced/docs/eo-next-table.md, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/index.spec.tsx, bricks/advanced/src/next-table/interface.ts
Closes BRICK-83
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): next-table support span

bricks/form-platform/src/user-or-user-group-select/index.spec.tsx, bricks/form-platform/src/user-or-user-group-select/index.tsx, bricks/form-platform/src/user-or-user-group-select/styles.shadow.css, bricks/form/src/select/index.spec.ts, bricks/form/src/select/index.tsx
Closes BRICK-50
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): eo-user-or-user-group-select问题修复

bricks/form-platform/src/user-or-user-group-select/index.tsx
=> chore(): eo-user-or-user-group-select code fix

bricks/advanced/docs/eo-next-table.md, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/index.spec.tsx, bricks/advanced/src/next-table/index.tsx, bricks/advanced/src/next-table/interface.ts, bricks/advanced/src/next-table/utils.ts
Closes BRICK-86
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): next-table support tree data

bricks/advanced/docs/eo-next-table.md, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/index.spec.tsx, bricks/advanced/src/next-table/index.tsx, bricks/advanced/src/next-table/interface.ts, bricks/advanced/src/next-table/utils.ts
Closes BRICK-86
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): next-table support sortable

bricks/basic/deploy-default/package.conf.yaml, bricks/basic/src/bootstrap.ts, bricks/basic/src/v3-widget-mate/index.ts
=> feat(): new brick: v3-widget-mate

bricks/ui-test/src/interface.ts, bricks/ui-test/src/utils/parseSuiteAst.spec.ts, bricks/ui-test/src/utils/parseSuiteAst.ts
Refs NEXT_BUILDER-4109
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support only / skip

bricks/basic/src/avatar/index.tsx, bricks/basic/src/avatar/sl-resize-observer.ts, bricks/basic/src/avatar/styles.shadow.css
Closes BRICK-94
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 字符型头像字体大小自动调整

bricks/advanced/docs/eo-next-table.md, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/index.spec.tsx, bricks/advanced/src/next-table/index.tsx, bricks/advanced/src/next-table/interface.ts
Closes BRICK-86
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): next-table support basic props

bricks/basic/src/page-title/index.tsx, bricks/containers/src/category/category.shadow.css, bricks/containers/src/micro-view/index.spec.ts, bricks/containers/src/micro-view/index.tsx, bricks/form/docs/eo-checkbox.md, bricks/form/src/checkbox/checkbox.shadow.css, bricks/form/src/checkbox/index.spec.tsx, bricks/form/src/checkbox/index.tsx, bricks/form/src/radio/index.shadow.css
=> fix():BRICK-101 eo-checkbox构件优化 ref BRICK-101

bricks/ui-test/src/custom-processors/__snapshots__/get-tree-data.spec.ts.snap, bricks/ui-test/src/custom-processors/get-tree-data.spec.ts, bricks/ui-test/src/custom-processors/get-tree-data.ts, bricks/ui-test/src/interface.ts
=> fix(): label support show flag

bricks/form/src/form-item/index.tsx
=> fix(): fix form repeat init value

bricks/form/package.json
=> chore(): update form dependencies

bricks/basic/src/sidebar/index.spec.tsx, bricks/basic/src/sidebar/index.tsx, bricks/basic/src/sidebar/sidebar-menu-group/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-item/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-submenu/styles.shadow.css, bricks/basic/src/sidebar/styles.shadow.css, bricks/basic/src/sidebar/utils.tsx
=> fix(): sidebar missing active & expanded state

bricks/nav/src/nav-menu/utils.tsx, bricks/visual-builder/src/workbench-action-list/index.tsx
Closes NEXT_BUILDER-4179
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): v3 框架下侧栏菜单不显示

bricks/basic/src/popover/index.spec.tsx, bricks/basic/src/popover/index.tsx
=> feat(popover): add arrow color property

bricks/form/src/icon-select/index.tsx, bricks/icons/docs/eo-icon.md, bricks/icons/docs/eo-img-icon.md, bricks/icons/package.json, bricks/icons/src/data-providers/get-libs.ts, bricks/icons/src/general-icon/index.spec.ts, bricks/icons/src/general-icon/index.tsx, bricks/icons/src/general-icon/styles.shadow.css, bricks/icons/src/icons.ts, bricks/icons/src/img-icon/index.spec.tsx, bricks/icons/src/img-icon/index.tsx, bricks/icons/src/img-icon/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes AGILE-1374
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): icon support imgSrc

bricks/ui-test/src/data-providers/export-as-file.spec.ts, bricks/ui-test/src/data-providers/export-as-file.ts
Refs NEXT_BUILDER-4128
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): show permission prompt if no permission

bricks/presentational/src/pagination/index.spec.tsx, bricks/presentational/src/pagination/index.tsx
Closes APM-209
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-pagination support showSizeChanger

bricks/basic/src/counter-badge/index.spec.tsx, bricks/basic/src/counter-badge/index.tsx, bricks/nav/src/launchpad/site-map/SiteMap.module.css, bricks/nav/src/launchpad/site-map/SiteMap.tsx
=> fix(): count overflowCount not work well && modify style

bricks/basic/src/bootstrap.ts, bricks/basic/src/data-providers/apply-ui-version/apply-ui-version.spec.ts, bricks/basic/src/data-providers/apply-ui-version/apply-ui-version.ts, bricks/basic/src/data-providers/apply-ui-version/css/ui-v8-2.css, bricks/basic/src/data-providers/apply-ui-version/css/ui-v8.css
=> feat(): support ui-adapter

bricks/ui-test/src/data-providers/export-as-file.ts, bricks/ui-test/src/utils/parseSuiteAst.ts
=> fix(): little optimization

bricks/form/docs/eo-time-range-picker.md, bricks/form/package.json, bricks/form/src/bootstrap.ts, bricks/form/src/time-range-picker/i18n.ts, bricks/form/src/time-range-picker/index.spec.tsx, bricks/form/src/time-range-picker/index.tsx, bricks/form/src/time-range-picker/styles.shadow.css, shared/common-bricks/common-bricks.json
=> feat():support eo-time-range-picker ref BRICK-53

bricks/basic/docs/eo-easyops-avatar.md, bricks/basic/package.json, bricks/basic/src/bootstrap.ts, bricks/basic/src/easyops-avatar/index.spec.tsx, bricks/basic/src/easyops-avatar/index.tsx, bricks/basic/src/easyops-avatar/styles.shadow.css, bricks/basic/src/easyops-avatar/useUserInfoByNameOrInstanceId.spec.tsx, bricks/basic/src/easyops-avatar/useUserInfoByNameOrInstanceId.ts, shared/common-bricks/common-bricks.json, shared/general/package.json, shared/general/src/makeThrottledAggregation.spec.ts, shared/general/src/makeThrottledAggregation.ts
Closes NEXT_BUILDER-4184
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support eo-easyops-avatar

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/card-item/index.tsx, bricks/data-view/src/app-wall/index.spec.tsx, bricks/data-view/src/app-wall/index.tsx, bricks/data-view/src/app-wall/interface.ts, bricks/data-view/src/app-wall/utils.spec.ts, bricks/data-view/src/app-wall/utils.ts
Closes APM-216
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): app-wall support cardBrickName && disabledDefaultClickEvent

bricks/advanced/src/table/table.shadow.css, bricks/basic/src/data-providers/apply-ui-version/css/ui-v8-2.css, bricks/basic/src/data-providers/apply-ui-version/css/ui-v8.css, bricks/containers/src/category/category.shadow.css, bricks/containers/src/tab/tab-group/tab.shadow.css, bricks/form/src/form-item/FormItem.shadow.css, bricks/form/src/general-switch/styles.shadow.css, bricks/form/src/select/index.shadow.css
=> feat(): update Style

bricks/ui-test/src/data-providers/data/commands/custom.ts, bricks/ui-test/src/data-providers/data/commands/cypress/actions.ts, bricks/ui-test/src/data-providers/data/commands/cypress/assertions.ts, bricks/ui-test/src/data-providers/data/commands/cypress/others.ts, bricks/ui-test/src/data-providers/data/commands/cypress/queries.ts, bricks/ui-test/src/data-providers/data/commands/third-party.ts
=> fix(): add description for commands

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/index.spec.tsx, bricks/data-view/src/app-wall/index.tsx
Closes APM-215
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): app-wall support containerId

bricks/basic/src/bootstrap.ts, bricks/basic/src/data-providers/lock-body-scroll/body-scroll.css, bricks/basic/src/data-providers/lock-body-scroll/lock-body-scroll.spec.ts, bricks/basic/src/data-providers/lock-body-scroll/lock-body-scroll.ts
=> feat():support basic.lock-body-scroll provider ref BRICK-58

bricks/containers/docs/eo-card.md, bricks/containers/src/card/card.shadow.css, bricks/containers/src/card/index.spec.tsx, bricks/containers/src/card/index.tsx, bricks/containers/src/drawer/index.spec.ts, bricks/containers/src/drawer/index.tsx, bricks/containers/src/modal/index.spec.tsx, bricks/containers/src/modal/index.tsx, bricks/form/src/textarea/textarea.shadow.css
=> fix():eo-modal滚动穿透、eo-drawer滚动穿透、eo-textarea、eo-card样式修改 ref BRICK-58

bricks/basic/src/bootstrap.ts, bricks/basic/src/data-providers/set-theme-by-apps.spec.ts, bricks/basic/src/data-providers/set-theme-by-apps.ts
=> feat(): add a new provider: set-theme-by-apps

bricks/basic/src/tag-list/index.shadow.css, bricks/basic/src/tag-list/index.spec.ts, bricks/basic/src/tag-list/index.tsx
=> feat(): tag support circle

bricks/ui-test/src/data-providers/export-as-file.ts, bricks/ui-test/src/utils/parseSuiteAst.spec.ts, bricks/ui-test/src/utils/parseSuiteAst.ts
Refs NEXT_BUILDER-4210
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support use `code` in chain call

bricks/visual-builder/src/workbench-history-action/i18n.ts, bricks/visual-builder/src/workbench-history-action/index.tsx, bricks/visual-builder/src/workbench-history-action/utils.ts
=> fix(): ts 单位修改 && 文案修改

bricks/vb-experiment/src/bootstrap.ts, bricks/vb-experiment/src/data-providers/export-widgets.ts
=> feat(): new provider: export-widgets

bricks/containers/src/banner/styles.shadow.css, bricks/containers/src/main-view/styles.shadow.css
=> fix(): refine banner style

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/index.tsx, bricks/data-view/src/simple-card-item/index.tsx, bricks/data-view/src/simple-card-item/styles.shadow.css
Closes APM-215
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): app-wall support noRotate && modify style

bricks/ui-test/src/bootstrap.ts, bricks/ui-test/src/data-providers/insert-node.spec.ts, bricks/ui-test/src/data-providers/insert-node.ts
Refs NEXT_BUILDER-4216
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): 支持命令下方插入命令

bricks/basic/src/app-bar-wrapper/styles.shadow.css
=> fix(): fix absolute app-bar

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/index.tsx
Closes APM-215
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(data-view): app-wall support boundMargin

bricks/basic/src/menu-item/menuItem.shadow.css, bricks/nav/src/nav-menu/nav-menu.shadow.css
=> fix(): revert menu-item hover style

bricks/ui-test/src/data-providers/export-as-file.ts
=> fix(): 适配 prettier 3.0

bricks/nav/src/nav-menu/nav-menu.shadow.css
=> fix(): no active style for nav menu items

bricks/basic/src/sidebar-sub-menu/styles.shadow.css
=> fix(): set active style for active sub menu items

bricks/containers/deploy-default/package.conf.yaml, bricks/containers/src/card/card.shadow.css, bricks/containers/src/card/index.spec.tsx, bricks/containers/src/card/index.tsx
Drop support for card footer and compact mode
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(card): support new prop: outline

bricks/basic/src/image/ImageComponent.spec.tsx, bricks/basic/src/image/ImageComponent.tsx, bricks/basic/src/image/ImageList.tsx, bricks/basic/src/image/ImageListContext.ts, bricks/basic/src/image/Preview.tsx, bricks/basic/src/image/index.tsx, bricks/form/src/upload/Upload.tsx, bricks/form/src/upload/upload-image/index.spec.tsx, bricks/form/src/upload/upload-image/index.tsx
=> feat(): support upload-image preview

bricks/visual-builder/src/workbench-history-action/index.tsx, bricks/visual-builder/src/workbench-history-action/utils.ts
Closes NEXT_BUILDER-4238
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): type fix && not allow rollback to rollback

bricks/basic/docs/eo-button.md, bricks/basic/src/button/index.spec.ts, bricks/basic/src/button/index.tsx
Refs BRICK-81
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): button support tooltip

bricks/containers/deploy-default/package.conf.yaml
=> fix(tabs): depends on new brick_next

bricks/visual-builder/src/data-providers/preview/connect.spec.ts, bricks/visual-builder/src/data-providers/preview/connect.ts, bricks/visual-builder/src/data-providers/preview/interfaces.ts
=> fix(preview): handle content scroll

bricks/basic/src/button/index.tsx, bricks/form/src/upload/Upload.tsx, bricks/form/src/upload/upload-file/i18n.ts, bricks/form/src/upload/upload-file/index.spec.tsx, bricks/form/src/upload/upload-file/index.tsx, bricks/form/src/upload/utils.spec.ts, bricks/form/src/upload/utils.ts
Refs BRICK-105
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support limitSize and related button properties

bricks/containers/docs/eo-tab-list.md, bricks/containers/src/tab/tab-group/index.spec.ts, bricks/containers/src/tab/tab-group/index.tsx, bricks/containers/src/tab/tab-list/index.spec.ts, bricks/containers/src/tab/tab-list/index.tsx
Closes NEXT_BUILDER-4292
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support tab.select event

bricks/basic/docs/eo-button.md, bricks/basic/docs/eo-dropdown-actions.md, bricks/basic/docs/eo-dropdown-button.md, bricks/basic/docs/eo-mini-actions.md, bricks/containers/docs/eo-content-layout.md, bricks/containers/docs/eo-drawer.md, bricks/containers/docs/eo-main-view.md, bricks/containers/docs/eo-modal.md, bricks/containers/docs/eo-narrow-view.md, bricks/containers/docs/eo-page-view.md, bricks/containers/src/content-layout/index.tsx, bricks/containers/src/main-view/index.tsx, bricks/containers/src/narrow-view/index.tsx, bricks/containers/src/page-view/index.tsx, bricks/nav/docs/eo-nav-menu.md
=> docs(): refine docs

bricks/basic/package.json, bricks/basic/src/sidebar/index.spec.tsx, bricks/basic/src/sidebar/index.tsx
=> fix(): sidebar show app icon

bricks/basic/src/app-bar-wrapper/styles.shadow.css, bricks/nav/src/nav-menu/index.tsx
=> fix(app-bar): fix style

bricks/basic/src/popover/index.tsx, bricks/nav/src/nav-menu/index.tsx, bricks/nav/src/nav-menu/nav-menu.shadow.css
=> fix(): nav-menu & popover style

bricks/basic/src/popover/index.spec.tsx, bricks/basic/src/popover/index.tsx, bricks/visual-builder/src/workbench-history-action/styles.shadow.css
=> fix(): style fix

bricks/v2-adapter/src/data-providers/legacy-brick-kit/LegacyUseBrick.tsx
=> fix(): ignore stale useBrick render

bricks/basic/src/sidebar/sidebar-menu-group/index.spec.tsx, bricks/basic/src/sidebar/sidebar-menu-group/index.tsx, bricks/basic/src/sidebar/sidebar-menu-group/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-item/styles.shadow.css, bricks/basic/src/sidebar/sidebar-menu-submenu/styles.shadow.css
=> feat(sidebar): group support collapsed

bricks/basic/src/sidebar/index.tsx
Closes MONITOR-7267
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): sidebar use native event

bricks/basic/src/sidebar/index.tsx
Closes MONITOR-7267
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): do not store hovered state

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/simple-card-item/index.tsx
MONITOR-7335
请勾选以下两组选项其中之一：
或者：
>
>
=> style(): data-view.simple-card-item 添加desStyle样式属性

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/simple-card-item/index.tsx
MONITOR-7335
请勾选以下两组选项其中之一：
或者：
>
>
=> style(): data-view.simple-card-item 添加titleStyle样式属性

bricks/data-view/src/app-wall/app-wall.shadow.css, bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/simple-card-item/index.tsx, bricks/data-view/src/simple-card-item/styles.shadow.css
MONITOR-7362
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): app-wall 应用墙构调整

bricks/containers/src/main-view/index.spec.tsx, bricks/containers/src/main-view/index.tsx, bricks/containers/src/main-view/styles.shadow.css
=> fix(main-view): show footer shadow only when it's pinned

bricks/visual-builder/src/workbench-history-action/i18n.ts, bricks/visual-builder/src/workbench-history-action/index.spec.tsx, bricks/visual-builder/src/workbench-history-action/index.tsx, bricks/visual-builder/src/workbench-history-action/styles.shadow.css, bricks/visual-builder/src/workbench-history-action/utils.ts
Closes NEXT_BUILDER-4358
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support rollback all

bricks/containers/src/main-view/index.tsx, bricks/containers/src/main-view/styles.shadow.css, bricks/containers/src/page-view/index.spec.tsx, bricks/containers/src/page-view/index.tsx, bricks/containers/src/page-view/styles.shadow.css
=> feat(): move footer to eo-page-view from eo-main-view

bricks/ui-test/src/constants.ts, bricks/ui-test/src/data-providers/preview/inspector.ts
Refs NEXT_BUILDER-4309
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): refactor query brick with inspect mode

bricks/vs/src/code-editor/index.css
=> feat(vsCodeEditor): add border

bricks/ui-test/src/data-providers/get-flat-nodes-in-tree.spec.ts, bricks/ui-test/src/data-providers/get-flat-nodes-in-tree.ts
Refs NEXT_BUILDER-4385
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): sort optimization

bricks/basic/src/dropdown-actions/index.spec.tsx, bricks/basic/src/dropdown-actions/index.tsx, bricks/basic/src/popover/index.tsx
=> fix(): dropdown actions 没有自动收起

bricks/basic/src/popover/index.spec.tsx, bricks/basic/src/popover/index.tsx, bricks/basic/src/popover/popup.ts
=> fix(): 更新 popup active 没有动画

bricks/nav/src/launchpad-button-v2/Launchpad.spec.tsx, bricks/nav/src/launchpad-button-v2/styles.shadow.css, bricks/nav/src/launchpad-button-v2/useLaunchpadInfo.ts
=> fix(launchpad-v2): refine style

bricks/containers/src/banner/styles.shadow.css, bricks/containers/src/content-layout/styles.shadow.css, bricks/containers/src/main-view/styles.shadow.css, bricks/containers/src/page-view/styles.shadow.css
=> fix(): flex gap fallback

bricks/nav/src/launchpad-button-v2/styles.shadow.css
=> fix(): fix recent visits overflow

bricks/vs/src/code-editor/index.spec.tsx, bricks/vs/src/code-editor/index.tsx, bricks/vs/src/code-editor/utils/brickNextSourceMap.ts, bricks/vs/src/code-editor/utils/brickNextYaml.ts, bricks/vs/src/code-editor/utils/editorId.ts, bricks/vs/src/code-editor/workers/index.ts, bricks/vs/src/code-editor/workers/parseYaml.worker.ts
=> feat(): monaco editor computed move to worker

bricks/containers/src/content-layout/styles.shadow.css, bricks/nav/src/launchpad-button-v2/styles.shadow.css
=> fix(): make launchpad compatible with browsers not support flex gap

bricks/basic/docs/eo-avatar-group.md, bricks/basic/src/avatar-group/index.spec.tsx, bricks/basic/src/avatar-group/index.tsx, bricks/basic/src/avatar-group/styles.shadow.css, bricks/basic/src/avatar/index.spec.tsx, bricks/basic/src/avatar/index.tsx, bricks/basic/src/avatar/styles.shadow.css, bricks/basic/src/bootstrap.ts, bricks/basic/src/easyops-avatar/index.spec.tsx, bricks/basic/src/easyops-avatar/index.tsx, bricks/basic/src/easyops-avatar/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-4394
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support eo-avatar-group

bricks/nav/src/launchpad-button-v2/Launchpad.spec.tsx, bricks/nav/src/launchpad-button-v2/MenuGroup.spec.tsx, bricks/nav/src/launchpad-button-v2/MenuGroup.tsx, bricks/nav/src/launchpad-button-v2/api.spec.ts, bricks/nav/src/launchpad-button-v2/interfaces.ts, bricks/nav/src/launchpad-button-v2/styles.shadow.css, bricks/nav/src/launchpad-button-v2/useLaunchpadInfo.ts, bricks/nav/src/launchpad-button-v2/wrapped-bricks.ts, bricks/nav/src/launchpad-config/MenuGroup.spec.tsx, bricks/nav/src/launchpad-config/MenuGroup.tsx, bricks/nav/src/launchpad-config/interfaces.ts, bricks/nav/src/launchpad-config/styles.shadow.css
=> fix(): handle empty icon, and refine style

bricks/basic/src/popover/popup.ts
=> fix(): don't maintain the animation's state

bricks/nav/src/nav-menu/nav-menu.shadow.css
=> fix(nav-menu): fix submenu overflow

bricks/nav/src/bootstrap.ts, bricks/nav/src/easyops-navbar-alerts/index.spec.tsx, bricks/nav/src/easyops-navbar-alerts/index.tsx, bricks/nav/src/easyops-navbar-alerts/styles.shadow.css
=> feat(): new brick: easyops-navbar-alerts

bricks/ui-test/src/bootstrap.ts, bricks/ui-test/src/data-providers/data/bricks/basic-bricks.ts, bricks/ui-test/src/data-providers/data/bricks/container-bricks.ts, bricks/ui-test/src/data-providers/data/bricks/forms.ts, bricks/ui-test/src/data-providers/data/bricks/index.ts, bricks/ui-test/src/data-providers/data/bricks/interfaces.ts, bricks/ui-test/src/data-providers/data/bricks/presentational-bricks.ts, bricks/ui-test/src/data-providers/get-brick-custom-commands.spec.ts, bricks/ui-test/src/data-providers/get-brick-custom-commands.ts, bricks/ui-test/src/data-providers/preview/inspector.ts, bricks/ui-test/src/data-providers/preview/interfaces.ts, bricks/ui-test/src/data-providers/preview/recorder.ts, bricks/ui-test/src/preview-container/InspectOutlineComponent.tsx
Refs NEXT_BUILDER-4334
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): custom brick command

bricks/advanced/docs/eo-workbench-layout.md, bricks/advanced/package.json, bricks/advanced/src/bootstrap.ts, bricks/advanced/src/workbench-layout/index.spec.tsx, bricks/advanced/src/workbench-layout/index.tsx, bricks/advanced/src/workbench-layout/styles.shadow.css, bricks/containers/package.json, bricks/form/package.json, bricks/form/src/checkbox/index.spec.tsx, bricks/form/src/checkbox/index.tsx, package.json, shared/common-bricks/common-bricks.json, yarn.lock
=> feat(): add workbench layout

bricks/nav/docs/eo-search-launchpad.md, bricks/nav/src/bootstrap.ts, bricks/nav/src/launchpad-quick-access/index.spec.tsx, bricks/nav/src/launchpad-quick-access/index.tsx, bricks/nav/src/launchpad-quick-access/styles.shadow.css, bricks/nav/src/search-launchpad/index.spec.tsx, bricks/nav/src/search-launchpad/index.tsx, bricks/nav/src/search-launchpad/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes NEXT_BUILDER-4407
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-launchpad-quick-access for workbench-widget

bricks/nav/src/launchpad-button-v2/api.ts, bricks/nav/src/launchpad-config/MenuGroup.tsx, bricks/nav/src/launchpad-config/interfaces.ts, bricks/nav/src/shared/getLocaleName.ts
=> fix(): support locales for launchpad config menu items

bricks/ui-test/src/data-providers/preview/interfaces.ts, bricks/ui-test/src/data-providers/save-recorded-commands.spec.ts, bricks/ui-test/src/data-providers/save-recorded-commands.ts
Refs NEXT_BUILDER-4311
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): support chain command

bricks/nav/src/bootstrap.ts, bricks/nav/src/launchpad-recent-visits/index.spec.tsx, bricks/nav/src/launchpad-recent-visits/index.tsx, bricks/nav/src/launchpad-recent-visits/styles.shadow.css, shared/common-bricks/common-bricks.json
=> feat(): eo-launchpad-recent-visits

bricks/nav/src/launchpad-button-v2/Launchpad.tsx
=> fix(launchpad): auto focus on search input

bricks/nav/src/launchpad-button-v2/styles.shadow.css, bricks/nav/src/launchpad-config/styles.shadow.css, bricks/nav/src/launchpad-recent-visits/styles.shadow.css, bricks/nav/src/search-launchpad/styles.shadow.css
redundancy for scrollbar
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): decrease launchpad item min-width

bricks/advanced/src/workbench-layout/index.tsx, bricks/advanced/src/workbench-layout/styles.shadow.css
=> feat(workbench-layout): add toolbar slot

bricks/containers/src/banner/host-context.css, bricks/containers/src/banner/index.tsx, bricks/containers/src/banner/styles.shadow.css, bricks/containers/src/card/card.shadow.css, bricks/containers/src/card/host-context.css, bricks/containers/src/card/index.tsx, bricks/containers/src/main-view/styles.shadow.css, bricks/containers/src/tab/tab-group/host-context.css, bricks/containers/src/tab/tab-group/index.tsx, bricks/containers/src/tab/tab-group/tab.shadow.css, bricks/nav/src/launchpad-button-v2/host-context.css, bricks/nav/src/launchpad-button-v2/index.tsx, bricks/nav/src/launchpad-button-v2/styles.shadow.css, bricks/nav/src/nav-menu/host-context.css, bricks/nav/src/nav-menu/index.tsx, bricks/nav/src/nav-menu/nav-menu.shadow.css, bricks/nav/src/nav-menu/site-map/SiteMapItem.shadow.css, bricks/nav/src/search-launchpad/host-context.css, bricks/nav/src/search-launchpad/index.tsx, bricks/nav/src/search-launchpad/styles.shadow.css, bricks/presentational/src/descriptions/descriptions.shadow.css, bricks/presentational/src/descriptions/host-context.css, bricks/presentational/src/descriptions/index.tsx
=> fix(): host-context fallback

bricks/nav/src/launchpad-config/MenuGroup.spec.tsx, bricks/nav/src/launchpad-config/MenuGroup.tsx, bricks/nav/src/launchpad-config/interfaces.ts, bricks/nav/src/launchpad-config/styles.shadow.css
=> fix(): launchpad actions for normal menu items

shared/ui-test/src/data/bricks/basic-bricks.ts, shared/ui-test/src/data/bricks/container-bricks.ts, shared/ui-test/src/data/bricks/forms.ts, shared/ui-test/src/data/bricks/presentational-bricks.ts, shared/ui-test/src/interfaces.ts
Refs NEXT_BUILDER-4425
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): add field

bricks/advanced/src/workbench-layout/index.tsx
Closes DESKTOP-349
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 编辑时卡片禁止交互

bricks/advanced/src/workbench-layout/index.tsx, bricks/advanced/src/workbench-layout/styles.shadow.css
=> feat(): update workbench style

bricks/advanced/src/workbench-layout/index.tsx, bricks/advanced/src/workbench-layout/styles.shadow.css, bricks/form/src/select/index.spec.ts, bricks/form/src/select/index.tsx
=> fix(): select Enter should not work when

bricks/nav/src/launchpad-button-v2/styles.shadow.css, bricks/nav/src/launchpad-config/styles.shadow.css
=> fix(): fix style in older browser without flex gap support

bricks/data-view/src/app-wall/app-wall.tsx, bricks/data-view/src/app-wall/interface.ts, bricks/data-view/src/simple-card-item/styles.shadow.css
MONITOR-7503
请勾选以下两组选项其中之一：
或者：
>
>
=> style(appwall): 优化hover效果

bricks/containers/src/content-layout/styles.shadow.css
=> fix(): refine content-layout compatibility

shared/ui-test/src/data/bricks/forms.ts
=> fix(): add forms.general-modal conf

bricks/advanced/src/workbench-layout/index.tsx, bricks/advanced/src/workbench-layout/styles.shadow.css
=> feat(workbench): add sticky for action wrapper

bricks/advanced/src/workbench-layout/index.tsx, bricks/advanced/src/workbench-layout/styles.shadow.css
=> feat(workbench-layout): update style

.github/workflows/ci.yml, bricks/visual-builder/src/data-providers/preview/connect.spec.ts, bricks/visual-builder/src/data-providers/preview/connect.ts, bricks/visual-builder/src/data-providers/preview/interfaces.ts, bricks/visual-builder/src/data-providers/preview/realTimeDataInspect.spec.ts, bricks/visual-builder/src/data-providers/preview/realTimeDataInspect.ts
=> feat(): real time data inspect

bricks/visual-builder/src/data-providers/preview/connect.spec.ts, bricks/visual-builder/src/data-providers/preview/connect.ts
=> fix(): reset real time data inspect when route rendered

bricks/basic/src/menu-group/index.tsx, bricks/basic/src/menu-item-sub-menu/index.tsx, bricks/basic/src/menu-item/index.tsx, bricks/basic/src/menu/index.tsx, bricks/containers/src/tab/tab-group/index.tsx, bricks/containers/src/tab/tab-item/index.tsx, bricks/form/src/form-item/index.tsx, bricks/nav/src/easyops-navbar-alerts/index.tsx, bricks/nav/src/launchpad-button-v2/index.tsx, bricks/nav/src/launchpad-config/index.tsx, bricks/nav/src/launchpad-quick-access/index.tsx, bricks/nav/src/launchpad-recent-visits/index.tsx, bricks/nav/src/launchpad/index.tsx, bricks/nav/src/search-launchpad/index.tsx, bricks/visual-builder/src/workbench-action-list/index.tsx, bricks/visual-builder/src/workbench-action/index.tsx, bricks/visual-builder/src/workbench-history-action/index.tsx, bricks/visual-builder/src/workbench-pane/index.tsx, bricks/visual-builder/src/workbench-sidebar/index.tsx, bricks/visual-builder/src/workbench-tree/index.tsx
=> chore(): add insider tag

bricks/vb-experiment/src/data-providers/utils/constants.ts, bricks/vb-experiment/src/data-providers/utils/extract.ts, bricks/vb-experiment/src/data-providers/utils/generators/generateTemplate.ts, bricks/vb-experiment/src/data-providers/utils/interfaces.ts, bricks/vb-experiment/src/data-providers/utils/transformers/transformBricks.ts, bricks/vb-experiment/src/data-providers/utils/transformers/transformJsxAttributes.ts
=> fix(): do not transform useBrick in events or similar

bricks/presentational/docs/eo-statistics-card.md, bricks/presentational/src/bootstrap.ts, bricks/presentational/src/statistics-card/index.spec.tsx, bricks/presentational/src/statistics-card/index.tsx, bricks/presentational/src/statistics-card/styles.shadow.css, shared/common-bricks/common-bricks.json
Closes DEPLOY_DASHBORAD-156
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-statistics-card

bricks/nav/src/nav-menu/site-map/GroupItem.tsx, bricks/nav/src/nav-menu/site-map/SiteMap.spec.tsx, bricks/nav/src/nav-menu/site-map/SiteMapItem.tsx
Refs MONITOR-7525
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): 修复切换菜单项卡死问题

bricks/presentational/docs/eo-descriptions.md, bricks/presentational/docs/eo-info-card-item.md, bricks/presentational/src/descriptions/descriptions.shadow.css, bricks/presentational/src/descriptions/host-context.css, bricks/presentational/src/descriptions/index.tsx, bricks/presentational/src/divider/styles.shadow.css, bricks/presentational/src/info-card-item/index.tsx, bricks/presentational/src/info-card-item/styles.shadow.css, bricks/presentational/src/pagination/host-context.css, bricks/presentational/src/pagination/index.tsx, bricks/presentational/src/pagination/styles.shadow.css
Closes BRICK-138
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): UI验收问题整改-presentational

bricks/basic/deploy-default/package.conf.yaml, bricks/basic/src/app-bar-wrapper/styles.shadow.css
=> chore(): update app-bar box-shadow

.github/workflows/ci.yml, bricks/icons/docs/eo-icon.md, bricks/icons/docs/eo-svg-icon.md, bricks/icons/src/antd-icon/index.spec.ts, bricks/icons/src/general-icon/index.spec.ts, bricks/icons/src/general-icon/index.tsx, bricks/icons/src/icons.ts, bricks/icons/src/img-icon/index.tsx, bricks/icons/src/shared/getImageUrl.ts, bricks/icons/src/svg-icon/index.spec.ts, bricks/icons/src/svg-icon/index.ts, bricks/icons/src/svg-icon/styles.shadow.css, shared/common-bricks/common-bricks.json
=> feat(): support svg image as icon by default

bricks/presentational/docs/eo-statistics-card.md, bricks/presentational/src/statistics-card/index.tsx, bricks/presentational/src/statistics-card/styles.shadow.css
Closes DEPLOY_DASHBORAD-169
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): support valueStyle & ellipsis

bricks/basic/src/popover/index.spec.tsx, bricks/basic/src/popover/index.tsx, bricks/basic/src/popover/popup.ts, bricks/form/src/select/index.shadow.css, bricks/form/src/select/index.spec.ts, bricks/form/src/select/index.tsx
=> fix(): fix popover hide and select hover

bricks/presentational/docs/eo-descriptions.md, bricks/presentational/docs/eo-info-card-item.md, bricks/presentational/src/descriptions/index.tsx, bricks/presentational/src/pagination/styles.shadow.css
Closes BRICK-138
请勾选以下两组选项其中之一：
或者：
>
>
=> fix(): UI验收问题整改-presentational

bricks/markdown/stories/eo-markdown-editor.ts, bricks/markdown/stories/images/eo-markdown-editor.svg, bricks/markdown/stories/images/index.ts, bricks/markdown/stories/index.ts
=> chore(markdown): add stoires

bricks/nav/src/sidebar/index.tsx
=> fix(): sidebar 取消固定没有马上收起

bricks/basic/src/mini-actions/index.tsx, bricks/presentational/docs/eo-statistics-card.md, bricks/presentational/src/statistics-card/index.tsx, bricks/presentational/src/statistics-card/styles.shadow.css
=> feat(): statistics-card 支持交互

bricks/basic/src/dropdown-actions/index.tsx
=> fix(): will render 0 when actions is empty

bricks/basic/src/data-providers/show-dialog/show-dialog.tsx
=> chore(): cancel button style in dialog

bricks/icons/src/easyops-icon/index.spec.ts, bricks/icons/src/shared/SvgCache.ts
=> fix(): keep color for masks, remove titles in svg

bricks/containers/docs/eo-card.md, bricks/containers/docs/eo-drawer.md, bricks/containers/docs/eo-main-view.md, bricks/containers/docs/eo-page-view.md, bricks/containers/src/banner/index.tsx, bricks/containers/src/card/card.shadow.css, bricks/containers/src/card/host-context.css, bricks/containers/src/card/index.tsx, bricks/containers/src/category/index.tsx, bricks/containers/src/content-layout/index.tsx, bricks/containers/src/drawer/drawer.shadow.css, bricks/containers/src/micro-view/index.tsx, bricks/containers/src/modal/modal.shadow.css, bricks/containers/src/spin/styles.shadow.css, bricks/containers/src/tab/tab-item/tab-item.shadow.css
=> chore(containers): update docs

bricks/basic/src/mini-actions/styles.shadow.css, bricks/presentational/docs/eo-card-item.md, bricks/presentational/src/card-item/index.spec.tsx, bricks/presentational/src/card-item/index.tsx, bricks/presentational/src/card-item/styles.shadow.css
refs STORE-27
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): eo-card-item 支持封面区域

bricks/nav/src/nav-menu/site-map/CollectService.spec.ts, bricks/nav/src/nav-menu/site-map/CollectService.ts
=> fix(): cache collection

bricks/nav/src/nav-menu/site-map/ItemTag.tsx
=> fix(): fix remove not work

bricks/nav/src/launchpad-button-v2/Launchpad.tsx, bricks/nav/src/launchpad-button-v2/styles.shadow.css
=> fix(): style optimization

bricks/nav/src/launchpad-button-v2/Launchpad.spec.tsx, bricks/nav/src/launchpad-button-v2/Launchpad.tsx, bricks/nav/src/launchpad-button-v2/index.tsx, bricks/nav/src/launchpad-button-v2/useLaunchpadInfo.ts
=> fix(): rename feature flag

bricks/nav/src/easyops-navbar-alerts/styles.shadow.css
refs: CMDB_INSTANCE-1246
请勾选以下两组选项其中之一：
或者：
>
>
=> chore(): 调整背景颜色

bricks/advanced/docs/eo-cascader.md, bricks/advanced/docs/eo-next-table.md, bricks/advanced/src/cascader/index.tsx, bricks/advanced/src/cascader/styles.shadow.css, bricks/advanced/src/next-table/Table.tsx, bricks/advanced/src/next-table/host-context.css, bricks/advanced/src/next-table/index.tsx, bricks/advanced/src/next-table/styles.shadow.css
=> chore(): update table style

bricks/icons/package.json
=> fix(): fix ci cache for icons

bricks/form/docs/eo-checkbox.md, bricks/form/src/checkbox/checkbox.shadow.css, bricks/form/src/checkbox/index.spec.tsx, bricks/form/src/checkbox/index.tsx, bricks/form/src/form-item/FormItem.shadow.less
=> chore(): update checkbox style

bricks/nav/src/launchpad-button-v2/Launchpad.tsx
=> fix(): 文案优化

bricks/form/src/form-item/FormItem.shadow.less, bricks/form/src/time-picker/fix-style.shadow.css, bricks/form/src/time-picker/index.tsx, bricks/form/src/time-picker/styles.shadow.css, bricks/form/src/time-range-picker/index.tsx, bricks/form/src/time-range-picker/styles.shadow.css
=> chore(): update time-picker style

bricks/basic/package.json, bricks/containers/package.json, bricks/data-view/package.json, bricks/form/package.json, bricks/illustrations/package.json, bricks/nav/package.json, bricks/presentational/package.json, bricks/recent-history/package.json, bricks/shoelace/package.json, bricks/ui-test/package.json, bricks/v2-adapter/package.json, bricks/vb-experiment/package.json, bricks/visual-builder/package.json, bricks/vs/package.json
=> chore(): 调整成 1.x

bricks/advanced/src/workbench-layout/styles.shadow.css, bricks/nav/src/launchpad-button-v2/LaunchpadContext.ts, bricks/nav/src/launchpad-button-v2/MenuGroup.tsx, bricks/nav/src/launchpad-quick-access/index.tsx, bricks/nav/src/search-launchpad/index.tsx, bricks/presentational/src/card-item/host-contenxt.css, bricks/presentational/src/card-item/index.tsx, bricks/presentational/src/card-item/styles.shadow.css
=> feat(): update wokrbench style & launchpad add readonly mode

bricks/nav/src/launchpad-button-v2/Launchpad.spec.tsx, bricks/nav/src/launchpad-button-v2/Launchpad.tsx, bricks/nav/src/launchpad-button-v2/styles.shadow.css
Closes C_CENTER-66
请勾选以下两组选项其中之一：
或者：
>
>
=> feat(): launchpad支持开放平台跳转
