shared/general/src/menu.spec.ts
shared/general/src/menu.ts
shared/general/src/types.ts

fix(): fix menu active match

---

bricks/diagram/src/diagram/index.spec.tsx
bricks/diagram/src/diagram/index.tsx
bricks/diagram/src/diagram/interfaces.ts
bricks/visual-builder/src/page-arch-node/index.spec.tsx
bricks/visual-builder/src/page-arch-node/index.tsx
bricks/visual-builder/src/page-arch-node/styles.shadow.css

feat(): show external label

---

bricks/nav/docs/eo-directory.md
bricks/nav/src/bootstrap.ts
bricks/nav/src/directory/index.spec.tsx
bricks/nav/src/directory/index.tsx
bricks/nav/src/directory/styles.shadow.css
shared/common-bricks/common-bricks.json

Closes CMDB_VIEW-76
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 新增三级菜单通用构件

---

bricks/form/docs/eo-radio.md
bricks/form/src/radio/host-context.css
bricks/form/src/radio/index.shadow.css
bricks/form/src/radio/index.spec.tsx
bricks/form/src/radio/index.tsx

chore(): update radio style

---

bricks/nav/src/frame-breadcrumb/index.spec.tsx
bricks/nav/src/frame-breadcrumb/index.tsx

feat(breadcrumb): show custom icon

---

bricks/diagram/src/diagram/constants.ts
bricks/diagram/src/diagram/index.spec.tsx
bricks/diagram/src/diagram/index.tsx
bricks/diagram/src/diagram/interfaces.ts
bricks/diagram/src/diagram/processors/getRenderedLinesAndMarkers.spec.ts
bricks/diagram/src/diagram/processors/getRenderedLinesAndMarkers.ts
bricks/diagram/src/diagram/styles.shadow.css
bricks/diagram/src/editable-label/index.spec.tsx
bricks/diagram/src/editable-label/index.tsx
bricks/diagram/src/editable-label/styles.shadow.css

feat(): support interactable lines

---

bricks/nav/src/nav-menu/index.tsx
bricks/nav/src/nav-menu/nav-menu.shadow.css
bricks/nav/src/sidebar/index.tsx

feat(): sidebar and navMenu render in firstTime

---

bricks/basic/docs/eo-context-menu.md
bricks/diagram/docs/eo-diagram.md
bricks/diagram/src/diagram/ClipPathComponent.tsx
bricks/diagram/src/diagram/ConnectLineComponent.tsx
bricks/diagram/src/diagram/LineComponent.tsx
bricks/diagram/src/diagram/MarkerComponent.tsx
bricks/diagram/src/diagram/index.spec.tsx
bricks/diagram/src/diagram/index.tsx
bricks/diagram/src/diagram/interfaces.ts
bricks/diagram/src/diagram/processors/getCenterOffsets.ts
bricks/diagram/src/diagram/processors/getClipPathList.ts
bricks/diagram/src/diagram/processors/getDagreGraph.ts
bricks/diagram/src/diagram/processors/getRenderedDiagram.ts
bricks/diagram/src/diagram/processors/getRenderedLineLabels.ts
bricks/diagram/src/diagram/processors/handleDiagramMouseDown.spec.ts
bricks/diagram/src/diagram/processors/handleDiagramMouseDown.ts
bricks/diagram/src/diagram/styles.shadow.css
bricks/visual-builder/src/page-arch-node/index.tsx

feat(): support manually connect line

---

bricks/containers/docs/eo-card.md
bricks/containers/src/card/card.shadow.css
bricks/containers/src/card/index.tsx

fix(): fix card implementation of fill container

---

bricks/containers/docs/eo-card.md
bricks/containers/src/card/card.shadow.css

fix(card): refine fill vertical

---

bricks/diagram/src/editable-label/index.spec.tsx
bricks/diagram/src/editable-label/index.tsx

fix(editable-label): dispatch label.editing.change

---

bricks/nav/docs/eo-directory-tree-internal-node.md
bricks/nav/docs/eo-directory-tree-leaf.md
bricks/nav/docs/eo-directory-tree.md
bricks/nav/package.json
bricks/nav/src/bootstrap.ts
bricks/nav/src/directory-tree/DirectoryTreeContext.ts
bricks/nav/src/directory-tree/Tree.tsx
bricks/nav/src/directory-tree/constants.ts
bricks/nav/src/directory-tree/directory-tree-internal-node/arrow.svg
bricks/nav/src/directory-tree/directory-tree-internal-node/index.spec.tsx
bricks/nav/src/directory-tree/directory-tree-internal-node/index.tsx
bricks/nav/src/directory-tree/directory-tree-internal-node/styles.shadow.css
bricks/nav/src/directory-tree/directory-tree-leaf/index.spec.tsx
bricks/nav/src/directory-tree/directory-tree-leaf/index.tsx
bricks/nav/src/directory-tree/directory-tree-leaf/styles.shadow.css
bricks/nav/src/directory-tree/index.spec.tsx
bricks/nav/src/directory-tree/index.tsx
bricks/nav/src/directory-tree/styles.shadow.css
bricks/nav/src/directory-tree/utils.ts
shared/common-bricks/common-bricks.json

Closes C_CENTER-103
请勾选以下两组选项其中之一：
或者：
>
>

feat(): eo-directory-tree

---

bricks/advanced/src/workbench-layout/index.spec.tsx
bricks/advanced/src/workbench-layout/index.tsx

feat(workbench-layout): small card auto size

---

bricks/basic/src/mini-actions/index.spec.tsx
bricks/basic/src/mini-actions/index.tsx
bricks/basic/src/mini-actions/styles.shadow.css
bricks/presentational/src/card-item/index.tsx

fix(): mini actions use eo-action

---

bricks/nav/src/directory-tree/Tree.tsx

fix(): eo-directory-tree 重复渲染 useBrick

---

bricks/diagram/src/diagram/index.spec.tsx
bricks/diagram/src/diagram/index.tsx
bricks/diagram/src/diagram/styles.shadow.css

feat(): allow diagram to toggle pannable

---

bricks/basic/src/mini-actions/styles.shadow.css
bricks/nav/src/directory-tree/Tree.tsx
bricks/nav/src/directory-tree/directory-tree-internal-node/styles.shadow.css
bricks/nav/src/directory-tree/directory-tree-leaf/styles.shadow.css
bricks/nav/src/directory-tree/index.spec.tsx
bricks/nav/src/directory-tree/index.tsx
bricks/nav/src/directory-tree/utils.ts

fix(): eo-directory-tree not render collapsed item

---

bricks/api-market/build.config.js
bricks/api-market/deploy-default/package.conf.yaml
bricks/api-market/docs/apis-directory-tree.md
bricks/api-market/package.json
bricks/api-market/src/apis-directory-tree/DirectoryTreeContext.ts
bricks/api-market/src/apis-directory-tree/Tree.tsx
bricks/api-market/src/apis-directory-tree/constants.ts
bricks/api-market/src/apis-directory-tree/index.spec.tsx
bricks/api-market/src/apis-directory-tree/index.tsx
bricks/api-market/src/apis-directory-tree/styles.shadow.css
bricks/api-market/src/apis-directory-tree/utils.ts
bricks/api-market/src/apis-directory-tree/wrapped-bricks.ts
bricks/api-market/src/bootstrap.ts
bricks/api-market/src/index.ts
bricks/api-market/tsconfig.json

feat(): apis_directory_tree

---

bricks/presentational/docs/eo-card-item.md
bricks/presentational/src/card-item/index.spec.tsx
bricks/presentational/src/card-item/index.tsx
bricks/presentational/src/card-item/styles.shadow.css

feat(): card item add tag

---

bricks/api-market/src/apis-directory-tree/index.tsx

chore(): release api-market

---

bricks/advanced/docs/eo-next-table.md
bricks/advanced/src/next-table/CacheUseBrickItem.spec.tsx
bricks/advanced/src/next-table/CacheUseBrickItem.tsx
bricks/advanced/src/next-table/Table.tsx

fix(table):  re-render useBrick

---

bricks/form/src/input/input.shadow.css

fix(input): fix style in Firefox

---

bricks/advanced/docs/eo-next-table.md
bricks/advanced/src/next-table/CacheUseBrickItem.spec.tsx
bricks/advanced/src/next-table/Table.tsx
bricks/advanced/src/next-table/index.spec.tsx
bricks/advanced/src/next-table/index.tsx
bricks/advanced/src/next-table/interface.ts

feat(next-table): allow set cell brick for dynamic columns

---

bricks/form/src/upload/upload-image/index.spec.tsx
bricks/form/src/upload/upload-image/index.tsx

feat(upload-image): add max count

---

bricks/nav/src/easyops-navbar-alerts/index.tsx
bricks/shoelace/src/shared/common.css

fix(): fix navbars alert re-render and fix shoelace common.css

---

bricks/v2-adapter/src/data-providers/dll.ts
bricks/v2-adapter/src/data-providers/legacy-brick-kit/LegacyUseBrick.tsx

fix(): manually use batched updates for legacy use-brick

---

shared/form/src/FormStore.ts

fix(formStore): fix pattern validate error

---

bricks/api-market/src/apis-directory-tree/Tree.tsx
bricks/api-market/src/apis-directory-tree/index.spec.tsx

fix(): add more action

---

bricks/api-market/src/apis-directory-tree/Tree.tsx

fix(): support disabled

---

bricks/diagram/docs/eo-diagram.md
bricks/diagram/package.json
bricks/diagram/src/diagram/hooks/useRenderedDiagram.ts
bricks/diagram/src/diagram/hooks/useUserView.spec.ts
bricks/diagram/src/diagram/hooks/useUserView.ts
bricks/diagram/src/diagram/index.spec.tsx
bricks/diagram/src/diagram/index.tsx
bricks/diagram/src/diagram/interfaces.ts
bricks/diagram/src/diagram/processors/createAsyncQueue.spec.ts
bricks/diagram/src/diagram/processors/createAsyncQueue.ts
bricks/diagram/src/diagram/processors/getForceGraph.ts
bricks/diagram/src/diagram/processors/getManualGraph.ts
bricks/diagram/src/diagram/processors/getRenderedEdges.ts
bricks/diagram/src/diagram/processors/handleNodesMouseDown.spec.ts
bricks/diagram/src/diagram/processors/handleNodesMouseDown.ts
bricks/diagram/src/diagram/processors/transformToCenter.spec.ts
bricks/diagram/src/diagram/processors/transformToCenter.ts

feat(): support manual graph

---

bricks/nav/src/app-bar-wrapper/styles.shadow.css
bricks/nav/src/sidebar/styles.shadow.css

chore(): fix nav z-index

---

bricks/api-market/src/apis-directory-tree/Tree.tsx
bricks/api-market/src/apis-directory-tree/index.spec.tsx

fix(): support import action

---

bricks/visual-builder/src/data-providers/preview/connect.spec.ts
bricks/visual-builder/src/data-providers/preview/connect.ts
bricks/visual-builder/src/data-providers/preview/inspector.ts
bricks/visual-builder/src/shared/workbench/WorkbenchTree.tsx
bricks/visual-builder/src/workbench-action-list/index.spec.tsx
bricks/visual-builder/src/workbench-action/index.spec.ts
bricks/visual-builder/src/workbench-action/index.tsx
bricks/visual-builder/src/workbench-pane/index.spec.ts
bricks/visual-builder/src/workbench-sidebar/index.spec.ts

fix(): inspect useBrick in shadow DOM

---

bricks/diagram/docs/eo-diagram.md
bricks/diagram/package.json
bricks/diagram/src/diagram/index.spec.tsx
bricks/diagram/src/diagram/index.tsx
bricks/diagram/src/diagram/processors/handleKeyboard.spec.ts
bricks/diagram/src/diagram/processors/handleKeyboard.ts
bricks/diagram/src/diagram/processors/sameTarget.spec.ts
bricks/diagram/src/diagram/processors/sameTarget.ts

fix(): observe line-labels resize

---

bricks/basic/docs/eo-actions.md
bricks/basic/docs/eo-dropdown-actions.md
bricks/basic/src/actions/index.spec.tsx
bricks/basic/src/actions/index.tsx
bricks/basic/src/actions/styles.shadow.css
bricks/basic/src/dropdown-actions/index.tsx

Closes INFRA-2443
请勾选以下两组选项其中之一：
或者：
>
>

feat(): eo-actions support subMenu

---

bricks/api-market/src/apis-directory-tree/Tree.tsx
bricks/api-market/src/apis-directory-tree/index.spec.tsx
bricks/basic/src/mini-actions/index.spec.tsx
bricks/basic/src/mini-actions/index.tsx
bricks/basic/src/mini-actions/styles.shadow.css

fix(): show tooltip

---

bricks/diagram/docs/eo-diagram.md
bricks/diagram/src/diagram/LineComponent.tsx
bricks/diagram/src/diagram/index.tsx
bricks/diagram/src/diagram/interfaces.ts
bricks/diagram/src/diagram/processors/normalizeLinesAndMarkers.spec.ts
bricks/diagram/src/diagram/processors/normalizeLinesAndMarkers.ts

feat(): overrides for active lines

---

bricks/nav/docs/nav-logo.md
bricks/nav/src/bootstrap.ts
bricks/nav/src/nav-logo/index.spec.tsx
bricks/nav/src/nav-logo/index.tsx
bricks/nav/src/nav-logo/styles.shadow.css

Closes CMDB_INSTANCE-1486
请勾选以下两组选项其中之一：
或者：
>
>

feat(): nav.nav-logo

---

bricks/form/src/radio/index.spec.tsx
bricks/form/src/radio/index.tsx

fix(): radio change event only emit value

---

bricks/visual-builder/docs/page-arch-node.md
bricks/visual-builder/src/page-arch-node/index.spec.tsx
bricks/visual-builder/src/page-arch-node/index.tsx
bricks/visual-builder/src/page-arch-node/styles.shadow.css

feat(page-arch): support show sub-nodes

---

bricks/form/docs/eo-dynamic-form-item.md
bricks/form/docs/eo-radio.md
bricks/form/docs/eo-select.md
bricks/form/docs/eo-submit-buttons.md
bricks/form/docs/eo-switch.md
bricks/presentational/docs/eo-statistics-card.md

fix(): refine docs headings

---

bricks/form/src/auto-complete/index.tsx
bricks/form/src/auto-complete/styles.shadow.css
bricks/form/src/form-item/index.spec.tsx
bricks/form/src/form-item/index.tsx
bricks/vs/src/code-editor/index.tsx
bricks/vs/src/code-editor/workers/parseYaml.worker.ts

feat(): update monaco-editor and auto-complete

---

bricks/form/src/radio/index.spec.tsx
bricks/form/src/radio/index.tsx

Reverts easyops-cn/next-bricks#814

Revert "fix(): radio change event only emit value"

---

bricks/form/src/radio/index.tsx

fix(radio):  form value only value

---

bricks/vs/docs/code-editor.md
bricks/vs/src/code-editor/index.css
bricks/vs/src/code-editor/utils/brickNextSourceMap.ts
bricks/vs/src/code-editor/utils/brickNextYaml.ts
bricks/vs/src/code-editor/workers/parseYaml.worker.ts

fix(code-editor): support string content

---

bricks/diagram/src/diagram/index.tsx

fix(): fix diagram infinite loop of active target events

---

bricks/basic/src/data-providers/show-dialog/show-dialog.spec.tsx
bricks/basic/src/data-providers/show-dialog/show-dialog.tsx
bricks/form/package.json
bricks/form/src/input/index.tsx
bricks/form/src/search/index.spec.tsx
bricks/form/src/search/index.tsx
shared/hooks/package.json
shared/hooks/src/index.ts
shared/hooks/src/useMergeRefs.spec.tsx
shared/hooks/src/useMergeRefs.ts
shared/hooks/tsconfig.build.json
shared/hooks/tsconfig.json

fix(): autoFocus not work

---

bricks/containers/docs/eo-category.md
bricks/containers/src/category/category.shadow.css
bricks/containers/src/category/index.spec.ts
bricks/containers/src/category/index.tsx

feat(category): add showIndex property

---

bricks/advanced/docs/capture-snapshot.md
bricks/advanced/src/data-providers/capture-snapshot.ts
bricks/advanced/src/data-providers/snapshot.ts

Closes MONITOR-7793
请勾选以下两组选项其中之一：
或者：
>
>

fix(): capture-snapshot 无法捕获到指定元素的截图

---

bricks/vs/src/code-editor/index.css
bricks/vs/src/code-editor/index.spec.tsx
bricks/vs/src/code-editor/index.tsx
bricks/vs/src/code-editor/utils/parseYaml.spec.ts
bricks/vs/src/code-editor/utils/parseYaml.ts
bricks/vs/src/code-editor/workers/index.mjs
bricks/vs/src/code-editor/workers/parseYaml.worker.ts

feat(monaco-editor): add unit test and css update

---

bricks/containers/docs/eo-tab-list.md
bricks/containers/src/tab/tab-group/index.tsx
bricks/containers/src/tab/tab-list/index.tsx

feat(eo-tab): add content-style property

---

bricks/basic/src/data-providers/show-notification/show-notification.tsx
bricks/vs/package.json
bricks/vs/src/code-editor/i18n.ts
bricks/vs/src/code-editor/index.css
bricks/vs/src/code-editor/index.spec.tsx
bricks/vs/src/code-editor/index.tsx
bricks/vs/src/code-editor/workers/parseYaml.worker.ts

feat(monaco-editor): add toolbar

---

bricks/advanced/src/next-table/Table.tsx

fix(): the design token of border-color must be css color type

---

bricks/basic/src/actions/index.spec.tsx
bricks/basic/src/actions/index.tsx
bricks/basic/src/actions/styles.shadow.css

feat(eo-actions): action.items support render url

---

bricks/vs/src/code-editor/index.tsx

fix(monaco-editor): onChange should emit

---

bricks/advanced/src/tree/index.spec.tsx
bricks/advanced/src/tree/index.tsx

feat(tree): support control expandedKeys and checkedKeys

---

bricks/advanced/src/data-providers/capture-snapshot.ts
bricks/advanced/src/data-providers/snapshot.ts

Closes CMDB_VIEW-109
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 卡片太多分辨率太多导出的PDF显示不全

---

bricks/advanced/src/tree/index.tsx

feat(tree): support nodes to reorder

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/bootstrap.ts
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/reducers/cells.spec.ts
bricks/diagram/src/draw-canvas/reducers/cells.ts
bricks/diagram/src/draw-canvas/reducers/index.ts
bricks/diagram/src/draw-canvas/reducers/interfaces.ts
bricks/diagram/src/draw-canvas/styles.shadow.css
bricks/diagram/src/experimental-node/index.tsx
bricks/diagram/src/experimental-node/styles.shadow.css
shared/common-bricks/common-bricks.json

feat(): new brick: eo-draw-canvas

---

bricks/basic/src/data-providers/show-notification/notification.module.css

fix(show-notification): fix z-index

---

bricks/advanced/docs/eo-tree.md
bricks/advanced/src/tree/index.spec.tsx
bricks/advanced/src/tree/index.tsx

Closes product-management-305
请勾选以下两组选项其中之一：
或者：
>
>

feat(): eo-tree support titleSuffixBrick

---

bricks/containers/src/modal/index.spec.tsx
bricks/containers/src/modal/index.tsx
bricks/containers/src/modal/modal.shadow.css

fix(): modal scrollable

---

bricks/form/src/textarea/index.spec.tsx
bricks/form/src/textarea/index.tsx

fix(eo-textarea): value was null not update

---

bricks/form/src/auto-complete/index.tsx
bricks/form/src/form-item/FormItem.shadow.less
bricks/form/src/form-item/index.tsx
bricks/visual-builder/src/contract-select/index.tsx

feat(form-item): update type

---

bricks/advanced/src/cascader/index.tsx
bricks/form/src/auto-complete/index.tsx
bricks/form/src/color-picker/index.tsx
bricks/form/src/date-picker/index.tsx
bricks/form/src/form-item/index.spec.tsx
bricks/form/src/form-item/index.tsx
bricks/form/src/time-picker/index.tsx
bricks/form/src/time-range-picker/index.tsx
bricks/visual-builder/src/contract-select/index.tsx
bricks/vs/src/code-editor/index.tsx
shared/form/src/FormStore.ts

fix(): form value should not with notRender item

---

bricks/nav/src/directory/index.spec.tsx
bricks/nav/src/directory/index.tsx
bricks/nav/src/directory/styles.shadow.css

CMDB_CONSUME-274
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 添加hideRightBorder隐藏右边框

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorArea.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorText.tsx
bricks/diagram/src/draw-canvas/decorators/index.tsx
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/cellToTarget.ts
bricks/diagram/src/draw-canvas/processors/handleKeyboard.ts
bricks/diagram/src/draw-canvas/processors/handleMouseDown.spec.ts
bricks/diagram/src/draw-canvas/processors/handleMouseDown.ts
bricks/diagram/src/draw-canvas/styles.shadow.css

feat(): support context menu event and edge selection

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/package.json
bricks/diagram/src/draw-canvas/ConnectLineComponent.spec.tsx
bricks/diagram/src/draw-canvas/ConnectLineComponent.tsx
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/initializeCells.ts
bricks/diagram/src/draw-canvas/reducers/cells.spec.ts
bricks/diagram/src/draw-canvas/reducers/cells.ts
bricks/diagram/src/draw-canvas/reducers/interfaces.ts
bricks/diagram/src/draw-canvas/styles.shadow.css

feat(draw-canvas): manually connect nodes

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/styles.shadow.css

feat(draw-canvas): edge line conf

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/initializeCells.ts
bricks/diagram/src/draw-canvas/processors/transformToCenter.spec.ts
bricks/diagram/src/draw-canvas/processors/transformToCenter.ts
bricks/diagram/src/draw-canvas/processors/updateCells.spec.ts
bricks/diagram/src/draw-canvas/processors/updateCells.ts
bricks/diagram/src/draw-canvas/reducers/cells.spec.ts
bricks/diagram/src/draw-canvas/reducers/cells.ts
bricks/diagram/src/draw-canvas/reducers/interfaces.ts

feat(): auto alignment when update cells

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/NodeComponent.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorText.spec.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorText.tsx
bricks/diagram/src/draw-canvas/decorators/index.tsx
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/styles.shadow.css

feat(draw-canvas): editable text

---

bricks/diagram/src/draw-canvas/NodeComponent.tsx

fix(draw-canvas): use deep memo for node data

---

bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/updateCells.spec.ts
bricks/diagram/src/draw-canvas/processors/updateCells.ts

fix(): place unpositioned nodes in a grid

---

bricks/icons/docs/eo-icon.md
bricks/icons/src/antd-icon/index.spec.ts
bricks/icons/src/antd-icon/index.ts
bricks/icons/src/easyops-icon/index.spec.ts
bricks/icons/src/easyops-icon/index.ts
bricks/icons/src/fa-icon/index.spec.ts
bricks/icons/src/fa-icon/index.tsx
bricks/icons/src/general-icon/index.spec.ts
bricks/icons/src/general-icon/index.tsx
bricks/icons/src/shared/interfaces.ts

feat(): support icon fallback

---

bricks/form/src/form/index.spec.tsx
bricks/form/src/form/index.tsx
bricks/vs/src/code-editor/index.tsx
shared/form/package.json
shared/form/src/FormStore.spec.ts
shared/form/src/FormStore.ts

feat(form):  setInitValue method add options

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.spec.ts
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.ts
bricks/diagram/src/draw-canvas/styles.shadow.css

feat(draw-canvas): support enable fade unrelated cells

---

bricks/icons/docs/eo-icon.md
bricks/icons/package.json
bricks/icons/src/general-icon/index.spec.ts
bricks/icons/src/general-icon/index.tsx
bricks/icons/src/svg-icon/index.spec.ts
bricks/icons/src/svg-icon/index.ts

fix(): support set icon fallback to image

---

bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/NodeComponent.tsx
bricks/diagram/src/draw-canvas/constants.ts
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/updateCells.spec.ts
bricks/diagram/src/draw-canvas/processors/updateCells.ts
bricks/diagram/src/draw-canvas/reducers/cells.spec.ts
bricks/diagram/src/draw-canvas/reducers/cells.ts
bricks/diagram/src/draw-canvas/reducers/interfaces.ts
bricks/diagram/src/draw-canvas/styles.shadow.css

feat(draw-canvas): responsive to node brick size

---

bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.spec.ts
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.ts
bricks/diagram/src/draw-canvas/styles.shadow.css

fix(draw-canvas): handle unrelated cells when connecting line

---

bricks/vs/src/code-editor/index.css
bricks/vs/src/code-editor/index.tsx

fix(): fix code editor update height and scroll to top

---

bricks/advanced/docs/eo-tree-select.md
bricks/advanced/src/bootstrap.ts
bricks/advanced/src/tree-select/index.spec.tsx
bricks/advanced/src/tree-select/index.tsx
bricks/advanced/src/tree-select/styles.shadow.css
shared/common-bricks/common-bricks.json

feat(): add eo-tree-select

---

bricks/nav/src/launchpad-button-v2/Launchpad.shadow.css
bricks/nav/src/launchpad-button-v2/Launchpad.tsx
bricks/nav/src/launchpad-button-v2/index.tsx

feat(launchpad): favorites add animation

---

bricks/diagram/docs/eo-display-canvas.md
bricks/diagram/src/display-canvas/index.spec.tsx
bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/experimental-node/styles.shadow.css

feat(display-canvas): support hover status

---

bricks/basic/src/avatar/index.spec.tsx
bricks/basic/src/avatar/index.tsx
bricks/basic/src/avatar/styles.shadow.css
bricks/basic/src/easyops-avatar/index.tsx

feat(avator): add showName

---

bricks/basic/docs/eo-button.md
bricks/basic/src/button/button.shadow.css
bricks/basic/src/interface.ts

feat(button): add icon type

---

bricks/vs/docs/code-editor.md
bricks/vs/src/code-editor/index.css
bricks/vs/src/code-editor/index.spec.tsx
bricks/vs/src/code-editor/index.tsx
bricks/vs/src/code-editor/utils/brickNextYaml.ts
bricks/vs/src/code-editor/utils/parseYaml.spec.ts
bricks/vs/src/code-editor/utils/parseYaml.ts
bricks/vs/src/code-editor/workers/parseYaml.worker.ts
jest/__mocks__/monaco-editor/esm/vs/editor/editor.api.js.js

feat(code-editor): update theme and support CTX.DS token

---

bricks/form/src/form/index.tsx

fix(form): setInitValue not update

---

bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/updateCells.spec.ts
bricks/diagram/src/draw-canvas/processors/updateCells.ts

fix(canvas): fix update cells when previous not centered

---

bricks/markdown/docs/eo-markdown-editor.md
bricks/markdown/src/markdown-editor/index.tsx
bricks/markdown/src/markdown-editor/markdown-editor.shadow.css

feat(markdown-editor): add readonly

---

bricks/diagram/docs/eo-display-canvas.md
bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/display-canvas/index.spec.tsx
bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/NodeComponent.tsx
bricks/diagram/src/draw-canvas/constants.ts
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/asserts.ts
bricks/diagram/src/draw-canvas/processors/handleMouseDown.spec.ts
bricks/diagram/src/draw-canvas/processors/handleMouseDown.ts
bricks/diagram/src/draw-canvas/processors/updateCells.spec.ts
bricks/diagram/src/draw-canvas/processors/updateCells.ts
bricks/diagram/src/shared/canvas/useAutoCenter.ts
bricks/diagram/src/shared/canvas/useLayout.ts
bricks/diagram/src/shared/canvas/useReady.ts

feat(canvas): force and dagre layout

---

bricks/diagram/src/display-canvas/index.spec.tsx
bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/constants.ts
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/shared/canvas/useLineMarkers.ts

feat(canvas): edge line conf

---

bricks/diagram/src/display-canvas/index.spec.tsx
bricks/diagram/src/shared/canvas/useLineMarkers.ts

fix(canvas): always put the default stroke marker at first

---

bricks/diagram/src/diagram/lines/getDirectLinePoints.ts
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/shared/canvas/useLineMarkers.ts

fix(canvas): parallel lines

---

bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/updateCells.spec.ts
bricks/diagram/src/draw-canvas/processors/updateCells.ts
bricks/diagram/src/shared/canvas/dagreLayout.ts
bricks/diagram/src/shared/canvas/forceLayout.ts
bricks/diagram/src/shared/canvas/useLayout.ts

fix(draw-canvas): refine new nodes layout

---

bricks/diagram/src/display-canvas/index.spec.tsx
bricks/diagram/src/shared/canvas/dagreLayout.ts

fix(canvas): dagre cannot render empty nodes

---

bricks/basic/src/popover/index.tsx
bricks/form/src/textarea/index.tsx
bricks/markdown/package.json
bricks/markdown/src/markdown-editor/index.tsx
bricks/markdown/src/markdown-editor/markdown-editor.shadow.css
shared/icons/src/icons/colored-common/robot-avatar.svg
shared/icons/src/icons/colored-common/user-avatar.svg

feat(): update chart basic dep code

---

bricks/containers/src/main-view/index.spec.tsx
bricks/containers/src/main-view/index.tsx
bricks/containers/src/main-view/styles.shadow.css

feat(eo-main-view): add showBanner and fillScreen

---

bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.spec.ts
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.ts

fix(draw-canvas): do not fade other cells when click on a decorator

---

bricks/diagram/src/display-canvas/index.spec.tsx
bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx

fix(display-canvas): new event: cell.click

---

bricks/basic/src/context-menu/index.spec.tsx
bricks/basic/src/context-menu/index.tsx

fix(): auto placement for eo-context-menu

---

bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/reducers/cells.spec.ts
bricks/diagram/src/draw-canvas/reducers/index.ts
bricks/diagram/src/draw-canvas/reducers/interfaces.ts
bricks/diagram/src/draw-canvas/reducers/layoutKey.ts
bricks/diagram/src/shared/canvas/useLayout.ts

fix(draw-canvas): ignore stale layout effect

---

bricks/diagram/src/display-canvas/index.spec.tsx
bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/updateCells.ts

fix(display-canvas): allow update cells prop

---

bricks/containers/docs/eo-main-view.md

chore(eo-main-view): update doc

---

bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/normalizeAlignOrigin.spec.ts
bricks/diagram/src/draw-canvas/processors/normalizeAlignOrigin.ts
bricks/diagram/src/shared/canvas/useLayout.ts

feat(): support layoutOptions.alignOrigin

---

bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/shared/canvas/useZoom.ts

fix(): allow dragging the canvas for display-canvas

---

bricks/containers/docs/eo-popup.md
bricks/containers/src/bootstrap.ts
bricks/containers/src/popup/index.spec.tsx
bricks/containers/src/popup/index.tsx
bricks/containers/src/popup/styles.shadow.css
shared/common-bricks/common-bricks.json

feat(eo-popup): init

---

bricks/diagram/src/draw-canvas/processors/updateCells.spec.ts
bricks/diagram/src/draw-canvas/processors/updateCells.ts

fix(draw-canvas): fix update with a single positioned nodes

---

bricks/containers/src/popup/index.spec.tsx
bricks/containers/src/popup/index.tsx
bricks/containers/src/popup/styles.shadow.css

fix(eo-popup): fix moving will change content width

---

bricks/advanced/src/data-providers/capture-snapshot.ts
bricks/advanced/src/data-providers/snapshot.ts

refs DASHBOARD-622
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support backgroundColor

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx

feat(): chat add enterInterval field

---

bricks/form/src/checkbox/index.tsx
bricks/form/src/date-picker/index.tsx
bricks/form/src/dynamic-form-item/index.tsx
bricks/form/src/general-switch/index.tsx
bricks/form/src/icon-select/index.tsx
bricks/form/src/input/index.tsx
bricks/form/src/radio/index.tsx
bricks/form/src/select/index.tsx
bricks/form/src/textarea/index.tsx

feat(): form-item add labelBrick

---

bricks/containers/src/drawer/drawer.shadow.css
bricks/containers/src/drawer/index.tsx

Refs ITSERVICE_NEXT-8277
请勾选以下两组选项其中之一：
或者：
>
>

fix(): drawer mask merge custom css propperties

---

bricks/nav/src/launchpad-button-v2/Launchpad.spec.tsx
bricks/nav/src/launchpad-button-v2/Launchpad.tsx

fix(): 开放平台去掉开关

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/ChatViewContext.ts
bricks/ai/src/chat-view/components/MessageItem/index.tsx
bricks/ai/src/chat-view/components/MessageList.tsx
bricks/ai/src/chat-view/components/QuickAnswerList/index.tsx
bricks/ai/src/chat-view/components/QuickAnswerList/quickAnswerList.shadow.css
bricks/ai/src/chat-view/index.tsx
bricks/ai/src/chat-view/styles.shadow.css

feat(chat-view): add  quickAnswerConfig

---

bricks/data-view/src/app-wall/app-wall.tsx
bricks/data-view/src/app-wall/index.tsx
bricks/data-view/src/app-wall/utils.ts

Closes MONITOR-8026
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 业务墙hover构件

---

bricks/data-view/src/app-wall/app-wall.tsx

fix(): optimized  popover display logic of app wall

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/components/MessageItem/index.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts

feat(chat-view): LLMStreamChat to LLMChatProxy

---

bricks/ai/src/chat-view/ChatService.ts

fix(chat-view): fix error data

---

bricks/form/src/upload/upload-image/index.tsx

Closes DASHBOARD-659
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 上传图片无法预览

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/components/MessageList.tsx
bricks/ai/src/chat-view/components/QuickAnswerList/index.tsx
bricks/ai/src/chat-view/components/QuickAnswerList/quickAnswerList.shadow.css

feat(chat-view): add more-btn

---

bricks/nav/src/frame-breadcrumb/index.spec.tsx
bricks/nav/src/frame-breadcrumb/index.tsx
yarn.lock

feat(): listen on nav config change

---

bricks/diagram/src/draw-canvas/index.tsx

feat(draw-canvas): support drag behavior of grab other than lasso

---

bricks/ai/src/chat-view/components/MessageList.tsx
bricks/ai/src/chat-view/components/SearchInput.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts

feat(chat-view): handle custom scroll

---

bricks/containers/package.json
bricks/containers/src/popup/index.spec.tsx
bricks/containers/src/popup/index.tsx
bricks/containers/src/popup/styles.shadow.css
yarn.lock

feat(): popup cache size

---

bricks/containers/src/popup/styles.shadow.css

chore(): update style

---

bricks/containers/src/popup/styles.shadow.css

fix(popup): fix content height not fill container

---

bricks/basic/src/counter-badge/styles.shadow.css

fix(): no pointer events for badge counter

---

bricks/ai/src/chat-view/components/QuickAnswerList/index.tsx
bricks/ai/src/chat-view/components/QuickAnswerList/quickAnswerList.shadow.css

feat(chat-view): quick-answer-list add ResizeObserver

---

bricks/form/src/select/index.spec.ts
bricks/form/src/select/index.tsx
bricks/form/src/utils/formatOptions.spec.ts
bricks/form/src/utils/formatOptions.ts
shared/form/src/FormStore.spec.ts
shared/form/src/FormStore.ts

fix(): formStore resetFields and select tag mode

---

bricks/form/src/select/index.spec.ts
bricks/form/src/select/index.tsx

fix(): tag mode value is undefined error

---

bricks/form/src/select/index.tsx

fix(select): fix default value null was error

---

bricks/presentational/docs/eo-current-time.md
bricks/presentational/src/bootstrap.ts
bricks/presentational/src/current-time/index.spec.tsx
bricks/presentational/src/current-time/index.tsx
bricks/presentational/src/current-time/styles.shadow.css
shared/common-bricks/common-bricks.json

Ref: DASHBOARD-590
请勾选以下两组选项其中之一：
或者：
>
>

feat(): feat current time bricks

---

bricks/ai/src/chat-view/components/QuickAnswerList/index.tsx
bricks/ai/src/chat-view/components/QuickAnswerList/quickAnswerList.shadow.css
bricks/ai/src/chat-view/components/loading.shadow.css
bricks/ai/src/chat-view/host-context.css
bricks/ai/src/chat-view/index.tsx
bricks/ai/src/chat-view/styles.shadow.css

chore(): update chat-view style

---

bricks/presentational/docs/eo-carousel-text.md
bricks/presentational/src/bootstrap.ts
bricks/presentational/src/carousel-text/index.spec.tsx
bricks/presentational/src/carousel-text/index.tsx
bricks/presentational/src/carousel-text/styles.shadow.css
shared/common-bricks/common-bricks.json

Ref: DASHBOARD-588
请勾选以下两组选项其中之一：
或者：
>
>

feat(): feat carousel text

---

bricks/ai/src/chat-view/components/MessageItem/Toolbar.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/styles.shadow.css

feat(chat-view): update default session

---

bricks/ai/src/chat-view/components/SessionList.tsx

fix(chat-view): title had newline and delete not work

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts

fix(): chat item like not work

---

bricks/v2-adapter/src/data-providers/load-bricks.tsx

feat(v2-adapter): add getRealValue

---

bricks/nav/deploy-default/package.conf.yaml

chore(): 组件已下线，无需依赖

---

bricks/basic/docs/eo-formatter-number.md
bricks/basic/src/bootstrap.ts
bricks/basic/src/formatter-number/index.spec.tsx
bricks/basic/src/formatter-number/index.tsx
bricks/basic/src/formatter-number/styles.shadow.css
shared/common-bricks/common-bricks.json

feat(): new brick: eo-formatter-number

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/ChatViewContext.ts
bricks/ai/src/chat-view/components/MessageItem/ContentTip.tsx
bricks/ai/src/chat-view/components/MessageItem/Toolbar.tsx
bricks/ai/src/chat-view/components/MessageItem/index.tsx
bricks/ai/src/chat-view/components/QuickAnswerList/index.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx

feat(chat-view): support readonly and update onMessage

---

bricks/basic/docs/eo-formatter-number.md
bricks/basic/src/formatter-number/index.tsx
bricks/presentational/src/humanize-time/index.tsx

docs(): refine description for eo-formatter-number

---

bricks/ai/package.json
bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/ChatViewContext.ts
bricks/ai/src/chat-view/components/Loading.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CodeBlock.shadow.css
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/InstanceList/Table.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/InstanceList/index.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/ProgressText.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/index.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/index.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/markdown.shadow.css
bricks/ai/src/chat-view/components/MessageItem/MsgItemContext.ts
bricks/ai/src/chat-view/components/MessageItem/index.tsx
bricks/ai/src/chat-view/components/MessageList.tsx
bricks/ai/src/chat-view/components/SearchInput.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx

feat(chat-view): support cmdb-instance-list

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CodeBlock.shadow.css
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/InstanceList/index.tsx

fix(chat-view): table empty data error

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/components/MessageItem/ContentTip.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CodeBlock.shadow.css
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/InstanceList/Table.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/InstanceList/index.tsx
bricks/ai/src/chat-view/components/MessageItem/Toolbar.tsx
bricks/ai/src/chat-view/components/MessageItem/index.tsx
bricks/ai/src/chat-view/components/SearchInput.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx
bricks/ai/src/chat-view/styles.shadow.css

请勾选以下两组选项其中之一：
-[x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。
或者：
>
>

feat(chat-view): support update sessionId

---

bricks/ai/src/chat-view/hooks/useChatViewInfo.ts

fix(chat-view): fix sessionId change

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CustomComponent.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/Table/index.tsx

fix(chat-view): fetch table data error

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CustomComponent.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/Table/index.tsx

fix(chat-view): fix table not render data

---

bricks/diagram/src/draw-canvas/processors/updateCells.ts
bricks/diagram/src/shared/canvas/useLayout.ts

fix(): skip layout if no cells

---

bricks/diagram/src/draw-canvas/index.tsx

fix(): do not re-center when dropping cells in manual layout

---

bricks/advanced/src/table/BrickTable.tsx
bricks/advanced/src/table/i18n.ts
bricks/advanced/src/table/index.spec.tsx

Refs NWYD-1665
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 表格页面条数提示语修复为中文

---

bricks/basic/src/button/index.spec.ts
bricks/basic/src/button/index.tsx
bricks/basic/src/constants.ts
bricks/basic/src/interface.ts

fix(button): handle unknown types/sizes/shapes

---

bricks/form/docs/eo-select.md
bricks/form/src/select/index.tsx

fix(): fix select suffix useBrick  notWork

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/index.tsx
bricks/ai/src/chat-view/components/MessageItem/index.tsx

Ref: INFRA-2945
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 修复chatting过程中link没有打开新窗口的问题

---

bricks/visual-builder/src/chat-conversation/index.tsx

fix(): do not update storyboard chunks if no new chunks

---

bricks/visual-builder/src/chat-conversation/index.tsx

fix(): fix auto scroll to bottom

---

bricks/visual-builder/package.json
bricks/visual-builder/src/contract-select/index.spec.tsx
bricks/visual-builder/src/interfaces.ts
bricks/visual-builder/src/shared/workbench/WorkbenchTree.spec.tsx
bricks/visual-builder/src/shared/workbench/WorkbenchTree.tsx
bricks/visual-builder/src/workbench-tree/WorkbenchTree.shadow.css

fix(): fix workbench tree styles

---

bricks/visual-builder/src/chat-conversation/index.tsx
bricks/visual-builder/src/chat-conversation/styles.shadow.css
bricks/visual-builder/src/chat-preview/index.tsx
bricks/visual-builder/src/data-providers/chat-preview/inspector.ts
bricks/visual-builder/src/data-providers/chat-preview/interfaces.ts
bricks/visual-builder/src/data-providers/inject-chat-preview-agent.ts
bricks/visual-builder/src/data-providers/preview/connect.ts
bricks/visual-builder/src/workbench-tree/WorkbenchTree.shadow.css

fix(chat-view): manually select target

---

bricks/form/src/select/index.shadow.css

fix(select): fix style

---

bricks/markdown/src/markdown-editor/index.tsx

Ref: POKEMON-625
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 修改markdown table break的热键

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/asserts.ts
bricks/diagram/src/draw-canvas/processors/findNodeOrAreaDecorator.ts
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.spec.ts
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.ts
bricks/diagram/src/shared/canvas/styles.shadow.css

Closes CMDB_VIEW-211
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 新版拓扑图支持区域连线

---

bricks/v2-adapter/src/data-providers/load-bricks.tsx

fix(): adapt rest of i18next

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorArea.tsx
bricks/diagram/src/draw-canvas/decorators/index.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/cellToTarget.ts
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.spec.ts
bricks/diagram/src/draw-canvas/processors/getUnrelatedCells.ts
bricks/diagram/src/draw-canvas/processors/handleKeyboard.spec.ts
bricks/diagram/src/draw-canvas/processors/handleKeyboard.ts
bricks/diagram/src/draw-canvas/processors/handleLasso.spec.ts
bricks/diagram/src/draw-canvas/processors/handleLasso.ts
bricks/diagram/src/draw-canvas/processors/handleMouseDown.spec.ts
bricks/diagram/src/draw-canvas/processors/handleMouseDown.ts
bricks/diagram/src/draw-canvas/processors/sameTarget.spec.ts
bricks/diagram/src/draw-canvas/processors/sameTarget.ts
bricks/diagram/src/draw-canvas/processors/targetIsActive.ts
bricks/diagram/src/draw-canvas/processors/updateCells.ts
bricks/diagram/src/draw-canvas/reducers/cells.spec.ts
bricks/diagram/src/draw-canvas/reducers/cells.ts
bricks/diagram/src/draw-canvas/reducers/interfaces.ts

feat(diagram): support lasso

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx

fix(chat-view): stop chat error

---

bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/handleLasso.spec.ts
bricks/diagram/src/draw-canvas/processors/handleLasso.ts
bricks/diagram/src/shared/canvas/useZoom.ts

feat(draw-canvas): support ctrlDragBehavior

---

bricks/visual-builder/docs/chat-conversation.md
bricks/visual-builder/src/chat-conversation/MessageComponent.tsx
bricks/visual-builder/src/chat-conversation/styles.shadow.css

fix(chat): treat user message as plain text

---

bricks/form/src/dynamic-form-item/index.tsx

fix(): revert data value passed by eo-dynamic-form-item

---

shared/icons/src/icons/itsc-form/button.svg

Refs ITSERVICE_NEXT-8335
请勾选以下两组选项其中之一：
或者：
>
>

feat(): add button icon

---

bricks/ai/src/chat-agent/index.spec.tsx
bricks/ai/src/chat-agent/index.tsx

feat(chat-agent): add method: newConversation

---

bricks/visual-builder/src/data-providers/preview/connect.spec.ts
bricks/visual-builder/src/data-providers/preview/connect.ts
bricks/visual-builder/src/data-providers/preview/interfaces.ts

feat(): support debug data value

---

bricks/presentational/src/card-item/index.tsx
bricks/presentational/src/card-item/styles.shadow.css

Closes CD-7941
请勾选以下两组选项其中之一：
或者：
>
>

feat(card-item): add selected property

---

bricks/presentational/src/card-item/host-contenxt.css
bricks/presentational/src/card-item/index.spec.tsx
bricks/presentational/src/card-item/styles.shadow.css

Refs CD-7941
请勾选以下两组选项其中之一：
或者：
>
>

fix(card-item): fix selected style of grayish styleType

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/ChatViewContext.ts
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CustomComponent.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/index.tsx
bricks/ai/src/chat-view/index.css
bricks/ai/src/chat-view/index.tsx
bricks/ai/src/chat-view/styles.shadow.css

feat(chat-view): add debug mode and custom component useBrick

---

bricks/basic/src/interface.ts

fix(): resume union literal types

---

bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/updateCells.ts
bricks/diagram/src/shared/canvas/dagreLayout.ts
bricks/diagram/src/shared/canvas/forceLayout.ts
bricks/diagram/src/shared/canvas/styles.shadow.css
bricks/diagram/src/shared/canvas/useLayout.ts

Closes SCHEMA_V-75
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 修复allowEdgeToArea:true的时,初始化报错的问题

---

bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/styles.shadow.css

feat(): support user message item render markdown

---

bricks/visual-builder/src/data-providers/preview/connect.ts

fix(): fix debug value in v2 next-core

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/components/SearchInput.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx

Ref: TOOL-1769
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 【AI辅助工具】AI辅助编写工具

---

bricks/form/build.config.js
bricks/form/package.json
yarn.lock

fix(): use fork of rc-trigger to fix events in nested shadow dom

---

bricks/ai/src/chat-view/ChatService.ts

feat(chatService): catch error status

---

bricks/form/src/form-item/index.tsx

fix(form-item):  not unsubscribe in first time

---

bricks/visual-builder/src/chat-conversation/index.tsx
cypress.config.ts
cypress/size-check.spec.js

fix(): add error boundary for chat preview

---

bricks/advanced/src/cascader/index.tsx
bricks/advanced/src/tree-select/index.tsx
bricks/basic/src/popover/popup.ts
bricks/form-platform/src/user-or-user-group-select/index.tsx
bricks/form/src/auto-complete/index.tsx
bricks/form/src/checkbox/index.tsx
bricks/form/src/color-picker/index.tsx
bricks/form/src/date-picker/index.tsx
bricks/form/src/dynamic-form-item/index.tsx
bricks/form/src/form-item/index.tsx
bricks/form/src/general-switch/index.tsx
bricks/form/src/icon-select/index.tsx
bricks/form/src/input/index.tsx
bricks/form/src/radio/index.tsx
bricks/form/src/select/index.tsx
bricks/form/src/submit-buttons/index.tsx
bricks/form/src/textarea/index.tsx
bricks/form/src/time-picker/index.tsx
bricks/form/src/time-range-picker/index.tsx
bricks/form/src/upload/upload-file/index.tsx
bricks/form/src/upload/upload-image/index.tsx
bricks/markdown/src/markdown-editor/index.tsx
bricks/visual-builder/src/contract-select/index.tsx
bricks/vs/src/code-editor/index.tsx
declarations/global.d.ts

feat(): add export message part for form-item bricks

---

bricks/basic/docs/eo-actions.md
bricks/basic/src/actions/index.spec.tsx
bricks/basic/src/actions/index.tsx
bricks/basic/src/actions/styles.shadow.css
bricks/basic/src/context-menu/index.spec.tsx
bricks/basic/src/context-menu/index.tsx
bricks/basic/src/dropdown-actions/index.tsx
bricks/basic/src/mini-actions/index.tsx

feat(): support action item drag

---

bricks/diagram/src/shared/canvas/ZoomBarComponent.shadow.css

refs CMDB_VIEW-238
请勾选以下两组选项其中之一：
或者：
>
>

style(diagram): 调整zoom-bar工具的大小

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CustomComponent.tsx
bricks/ai/src/chat-view/components/SearchInput.tsx
bricks/ai/src/chat-view/index.tsx

feat(chat-view):  support sendMsg

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/ChatViewContext.ts
bricks/ai/src/chat-view/components/SearchInput.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx

fix(chat-view): support ChatBody args

---

bricks/diagram/src/draw-canvas/processors/updateCells.ts

Refs CMDB_VIEW-239
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 临时解决一次性添加多层的节点手工布局报错

---

bricks/basic/src/context-menu/index.tsx

fix(): dragging status

---

bricks/visual-builder/src/bootstrap.ts
bricks/visual-builder/src/generate-snippets-context-menu/i18n.ts
bricks/visual-builder/src/generate-snippets-context-menu/index.spec.tsx
bricks/visual-builder/src/generate-snippets-context-menu/index.tsx
bricks/visual-builder/src/generate-snippets-context-menu/styles.shadow.css

feat():  snippet context menu

---

bricks/markdown/src/markdown-editor/index.tsx
bricks/markdown/src/markdown-editor/markdown-editor.shadow.css

Ref: POKEMON-625
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 修改editor边距;修复只能在第一行聚焦editor的问题

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/markdown.shadow.css

Ref: INFRA-3105
请勾选以下两组选项其中之一：
或者：
>
>

fix(): fix markdown table style

---

bricks/nav/src/nav-menu/nav-menu.shadow.css

fix(): refine css

---

shared/general/src/menu.spec.ts
shared/general/src/menu.ts

Closes BRICK-365
请勾选以下两组选项其中之一：
或者：
>
>

fix(): nav构件遇到空的items时会报错

---

bricks/ai/src/chat-view/ChatViewContext.ts
bricks/ai/src/chat-view/components/MessageItem/Toolbar.tsx
bricks/ai/src/chat-view/index.tsx
bricks/ai/src/chat-view/styles.shadow.css

Ref: INFRA-2822
请勾选以下两组选项其中之一：
或者：
>
>

fix(): support share ablity

---

bricks/ai/src/chat-view/ChatService.ts

Ref: INFRA-3111
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 只要是命令字，且命令字不等于easy_cmd_progress的时候就直接返回

---

bricks/basic/src/bootstrap.ts
bricks/basic/src/editors/eo-button/eoButton.schema.tsx
bricks/basic/src/editors/eo-button/index.tsx
bricks/basic/src/editors/index.ts
bricks/basic/tsconfig.json
bricks/visual-builder/docs/property-editor.md
bricks/visual-builder/package.json
bricks/visual-builder/src/bootstrap.ts
bricks/visual-builder/src/property-editor/components/AdvancedFormItem/AdvancedFormItem.shadow.css
bricks/visual-builder/src/property-editor/components/AdvancedFormItem/index.tsx
bricks/visual-builder/src/property-editor/components/CategoryTitle/CategoryTitle.shadow.css
bricks/visual-builder/src/property-editor/components/CategoryTitle/index.tsx
bricks/visual-builder/src/property-editor/components/common/CodeEditorComponent.tsx
bricks/visual-builder/src/property-editor/components/common/IconSelectComponent.tsx
bricks/visual-builder/src/property-editor/index.spec.tsx
bricks/visual-builder/src/property-editor/index.tsx
bricks/visual-builder/src/property-editor/style.css
bricks/visual-builder/src/property-editor/utils/schemaFormatter.ts
yarn.lock

feat(): support property-editor

---

bricks/visual-builder/src/data-providers/preview/connect.spec.ts
bricks/visual-builder/src/data-providers/preview/connect.ts
bricks/visual-builder/src/data-providers/preview/interfaces.ts

feat(): inspect runtime value

---

bricks/basic/src/text/index.tsx

Ref: BRICK-336
请勾选以下两组选项其中之一：
或者：
>
>

fix(): fix eo-text type

---

bricks/basic/src/editors/eo-button/index.tsx
bricks/visual-builder/src/property-editor/index.tsx

feat(): editor add dataList scope

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/ChatViewContext.ts
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CustomComponent.tsx
bricks/ai/src/chat-view/components/MessageItem/Toolbar.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx

feat(chat-view):  add robotId

---

bricks/ai/src/chat-view/components/SearchInput.tsx
bricks/ai/src/chat-view/index.tsx
bricks/ai/src/chat-view/styles.shadow.css

feat(chat-view): add inputToolbarBrick

---

bricks/basic/src/editors/eo-search-bar/eoSearchBar.schema.tsx
bricks/basic/src/editors/eo-search-bar/index.tsx
bricks/basic/src/editors/eo-spin/eoSpin.schema.tsx
bricks/basic/src/editors/eo-spin/index.tsx
bricks/basic/src/editors/eo-tag/eoTag.schema.tsx
bricks/basic/src/editors/eo-tag/index.tsx
bricks/basic/src/editors/eo-text/eoText.schema.tsx
bricks/basic/src/editors/eo-text/index.tsx
bricks/basic/src/editors/index.ts

Ref: BRICK-336
请勾选以下两组选项其中之一：
或者：
>
>

fix(): text spin and searchbar schema

---

bricks/visual-builder/src/property-editor/components/AdvancedFormItem/AdvancedFormItem.shadow.css
bricks/visual-builder/src/property-editor/components/AdvancedFormItem/index.tsx
bricks/visual-builder/src/property-editor/index.spec.tsx
bricks/visual-builder/src/property-editor/index.tsx

feat(): vb support property-editor

---

bricks/visual-builder/src/data-providers/preview/connect.spec.ts
bricks/visual-builder/src/data-providers/preview/connect.ts
bricks/visual-builder/src/data-providers/preview/interfaces.ts

fix(): enable form-builder preview

---

bricks/basic/src/editors/eo-button/eoButton.schema.tsx
bricks/basic/src/editors/eo-button/index.tsx
bricks/basic/src/editors/eo-search-bar/index.tsx
bricks/basic/src/editors/eo-spin/index.tsx
bricks/basic/src/editors/eo-tag/index.tsx
bricks/basic/src/editors/eo-text/index.tsx
bricks/visual-builder/src/property-editor/index.tsx

feat(): update Editor code & add onSubmitEffect

---

bricks/basic/src/editors/eo-category/eoCategory.schema.tsx
bricks/basic/src/editors/eo-category/index.tsx
bricks/basic/src/editors/eo-popover/eoPopover.schema.tsx
bricks/basic/src/editors/eo-popover/index.tsx
bricks/basic/src/editors/eo-search/eoSearch.schema.tsx
bricks/basic/src/editors/eo-search/index.tsx
bricks/basic/src/editors/eo-tag/eoTag.schema.tsx
bricks/basic/src/editors/eo-tag/index.tsx
bricks/basic/src/editors/eo-text/eoText.schema.tsx
bricks/basic/src/editors/index.ts
bricks/basic/test.config.js
bricks/form/src/search/index.tsx

Ref: BRICK-354
请勾选以下两组选项其中之一：
或者：
>
>

fix(): update schema

---

bricks/visual-builder/src/property-editor/index.tsx

feat(property-editor):  add onAdvancedChangeEffect

---

bricks/visual-builder/src/bootstrap.ts
bricks/visual-builder/src/data-providers/get-data-dependency.spec.ts
bricks/visual-builder/src/data-providers/get-data-dependency.ts

feat(): data dependency provider

---

bricks/v2-adapter/src/data-providers/legacy-brick-kit/getLegacyRuntime.ts

feat(v2-adapter): add customEditors

---

bricks/visual-builder/docs/property-editor.md

chore(property-editor): update doc

---

bricks/visual-builder/src/property-editor/index.spec.tsx
bricks/visual-builder/src/property-editor/index.tsx

feat(): fetch by editorPackages

---

bricks/basic/src/mini-actions/index.tsx
bricks/presentational/src/card-item/index.tsx

Closes CD-8330
请勾选以下两组选项其中之一：
或者：
>
>

feat(eo-mini-actions): Add url support for non-dropdown action

---

bricks/nav/src/nav-menu/index.spec.ts
bricks/nav/src/nav-menu/index.tsx

fix(): nav-menu filter menuItems

---

bricks/basic/src/link/index.tsx

Closes CD-8335
请勾选以下两组选项其中之一：
或者：
>
>

feat(link): add tooltip property

---

bricks/basic/src/editors/brick-general-search/brickGeneralSearch.schema.tsx
bricks/basic/src/editors/brick-general-search/index.tsx
bricks/basic/src/editors/brick-tag/brickTag.schema.tsx
bricks/basic/src/editors/brick-tag/index.tsx
bricks/basic/src/editors/category-container/categoryContainer.schema.tsx
bricks/basic/src/editors/category-container/index.tsx
bricks/basic/src/editors/eo-popover/index.tsx
bricks/basic/src/editors/eo-search/index.tsx
bricks/basic/src/editors/general-text/generalText.schema.tsx
bricks/basic/src/editors/general-text/index.tsx
bricks/basic/src/editors/index.ts
bricks/basic/src/editors/line-chart/index.tsx
bricks/basic/src/editors/line-chart/lineChart.schema.tsx
bricks/basic/src/editors/loading-container/index.tsx
bricks/basic/src/editors/loading-container/loadingContainer.schema.tsx
bricks/basic/src/editors/popover-container/index.tsx
bricks/basic/src/editors/popover-container/popoverContainer.schema.tsx
bricks/basic/src/editors/search-bar/index.tsx
bricks/basic/src/editors/search-bar/searchBar.schema.tsx

Ref: BRICK-338
请勾选以下两组选项其中之一：
或者：
>
>

fix(): fixV2Schema

---

bricks/basic/docs/eo-tag.md

docs(): Update eo-tag.md

---

bricks/basic/src/editors/eo-drawer/eoDrawer.schema.tsx
bricks/basic/src/editors/eo-drawer/index.tsx
bricks/basic/src/editors/eo-tab-list/eoTabList.schema.tsx
bricks/basic/src/editors/eo-tab-list/index.tsx
bricks/basic/src/editors/general-drawer/generalDrawer.schema.tsx
bricks/basic/src/editors/general-drawer/index.tsx
bricks/basic/src/editors/index.ts
bricks/basic/src/editors/tabs-container/index.tsx
bricks/basic/src/editors/tabs-container/tabsContainer.schema.tsx

Ref: BRICK-341
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 6.25 schema

---

bricks/basic/src/editors/brick-tag/brickTag.schema.tsx
bricks/basic/src/editors/eo-popover/eoPopover.schema.tsx
bricks/basic/src/editors/eo-tag/eoTag.schema.tsx
bricks/basic/src/editors/eo-text/eoText.schema.tsx
bricks/basic/src/editors/loading-container/loadingContainer.schema.tsx

Ref: BRICK-509
请勾选以下两组选项其中之一：
或者：
>
>

fix(): edit colorPicker

---

bricks/basic/src/editors/eo-button/eoButton.schema.tsx
bricks/visual-builder/src/property-editor/components/AdvancedFormItem/index.tsx
bricks/visual-builder/src/property-editor/components/common/ColorPickerComponent.tsx
bricks/visual-builder/src/property-editor/index.tsx
bricks/visual-builder/src/property-editor/utils/colorTransform.ts
bricks/visual-builder/src/property-editor/utils/colorTrasnform.spec.ts
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.spec.ts
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.ts

feat(): support colorPickComponent

---

bricks/visual-builder/src/property-editor/components/common/CodeEditorComponent.tsx
bricks/visual-builder/src/property-editor/index.tsx
bricks/vs/src/code-editor/index.tsx

fix(): code Editor output and update Editor refresh values

---

bricks/basic/src/editors/eo-divider/eoDivider.schema.tsx
bricks/basic/src/editors/eo-divider/index.tsx
bricks/basic/src/editors/eo-modal/eoModal.schema.tsx
bricks/basic/src/editors/eo-modal/index.tsx
bricks/basic/src/editors/eo-search-bar/index.tsx
bricks/basic/src/editors/eo-tag/index.tsx
bricks/basic/src/editors/eo-text/index.tsx
bricks/basic/src/editors/index.ts

Ref: BRICK-335
请勾选以下两组选项其中之一：
或者：
>
>

fix(): add divider and modal schema

---

bricks/basic/docs/eo-text.md
bricks/basic/src/link/index.tsx
bricks/basic/src/link/link.shadow.css
bricks/basic/src/text/index.spec.ts
bricks/basic/src/text/index.tsx

Closes CD-8334
请勾选以下两组选项其中之一：
或者：
>
>

feat(text): add editable property, change and update event

---

bricks/presentational/docs/eo-card-item.md
bricks/presentational/src/card-item/index.tsx
bricks/presentational/src/card-item/styles.shadow.css

Closes CD-8341
请勾选以下两组选项其中之一：
或者：
>
>

feat(card-item): add showActions and cardStyle properties

---

bricks/basic/src/editors/eo-button/eoButton.schema.tsx
bricks/basic/src/editors/eo-button/index.tsx
bricks/visual-builder/src/property-editor/components/AdvancedFormItem/index.tsx
bricks/visual-builder/src/property-editor/components/common/CodeEditorComponent.tsx
bricks/visual-builder/src/property-editor/components/common/ColorPickerComponent.tsx
bricks/visual-builder/src/property-editor/components/common/InputWithUrlComponent.tsx
bricks/visual-builder/src/property-editor/index.tsx
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.spec.ts
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.ts
bricks/vs/src/code-editor/index.tsx

feat(): code editor add hideLineNumber and fix property-editor

---

bricks/basic/src/editors/eo-divider/eoDivider.schema.tsx
bricks/basic/src/editors/eo-search-bar/eoSearchBar.schema.tsx
bricks/basic/src/editors/eo-text/eoText.schema.tsx
bricks/visual-builder/src/property-editor/components/AdvancedFormItem/AdvancedFormItem.shadow.css
bricks/visual-builder/src/property-editor/components/CategoryTitle/CategoryTitle.shadow.css
bricks/visual-builder/src/property-editor/components/common/InputWithUrlComponent.tsx
bricks/visual-builder/src/property-editor/components/common/TextAlignRadioComponent.tsx
bricks/visual-builder/src/property-editor/index.tsx
bricks/visual-builder/src/property-editor/style.css
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.spec.ts
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.ts

feat(): fix style and support textAlignRadio

---

bricks/basic/docs/eo-tag.md
bricks/basic/src/tag/index.spec.ts
bricks/basic/src/tag/index.tsx
bricks/basic/src/tag/tag.shadow.css

Refs CD-7993
请勾选以下两组选项其中之一：
或者：
>
>

feat(tag): add pink color

---

bricks/basic/src/editors/eo-card-item/eoCardItem.schema.tsx
bricks/basic/src/editors/eo-card-item/index.tsx
bricks/basic/src/editors/eo-popover/eoPopover.schema.tsx
bricks/basic/src/editors/index.ts

Ref: BRICK-466
请勾选以下两组选项其中之一：
或者：
>
>

fix(): add card item schema

---

bricks/vs/src/code-editor/index.tsx
bricks/vs/src/code-editor/utils/constants.ts
bricks/vs/src/code-editor/utils/jsSuggestInBrickYaml.ts

fix(): refine declare

---

bricks/diagram/src/draw-canvas/decorators/DecoratorText.spec.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorText.tsx
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/processors/asserts.ts

Closes CMDB_INSTANCE-1668
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 框选支持文字

---

bricks/visual-builder/src/property-editor/components/AdvancedFormItem/index.tsx
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.spec.ts
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.ts
bricks/vs/src/code-editor/index.tsx

feat(code-editor): add glyphMargin

---

bricks/ai/src/chat-view/styles.shadow.css

Ref: INFRA-3244
请勾选以下两组选项其中之一：
或者：
>
>

fix(): AI聊天框【停止生成】会跟助手名称重叠

---

bricks/advanced/docs/eo-text-tooltip.md
bricks/advanced/src/bootstrap.ts
bricks/advanced/src/text-tooltip/index.spec.tsx
bricks/advanced/src/text-tooltip/index.tsx
bricks/advanced/src/text-tooltip/styles.shadow.css
shared/common-bricks/common-bricks.json

Refs MONITOR-8634
请勾选以下两组选项其中之一：
或者：
>
>

feat(eo-text-tooltip): 新增一个文本展示构件，文本超出才展示tip

---

bricks/vb-experiment/src/data-providers/utils/plugins/smart-imports.ts
bricks/vs/src/code-editor/utils/constants.ts

fix(): add new keyword`SIZE`, add missing types for builtin keywords

---

bricks/vs/src/code-editor/index.tsx

fix(): code editor focus change

---

bricks/advanced/src/cascader/index.tsx
bricks/advanced/src/text-tooltip/index.tsx
bricks/advanced/src/tree-select/index.spec.tsx
bricks/advanced/src/tree-select/index.tsx

Refs MONITOR-8634
请勾选以下两组选项其中之一：
或者：
>
>

fix(eo-text-tooltip): 修复在v2构件中导致样式不对的问题

---

bricks/advanced/src/workbench-layout/index.tsx

Closes MONITOR-8243
请勾选以下两组选项其中之一：
或者：
>
>

fix(): layouts未监听，希望编辑情况下能动态改变参数

---

bricks/ai/src/chat-view/hooks/useChatViewInfo.ts

Ref: INFRA-3272
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 多agent的回答需要拆分消息框展示

---

bricks/ai/src/chat-view/components/MessageItem/Toolbar.tsx
bricks/ai/src/chat-view/components/MessageItem/index.tsx
bricks/ai/src/chat-view/styles.shadow.css

Ref: INFRA-3280
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 把重新提问按钮放到toolbar

---

bricks/vs/src/code-editor/index.tsx

fix(code-editor): only validate yaml, for now

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/display-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorContainer.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorText.tsx
bricks/diagram/src/draw-canvas/decorators/index.tsx
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/asserts.ts
bricks/diagram/src/draw-canvas/processors/handleMouseDown.ts
bricks/diagram/src/draw-canvas/processors/handleNodeContainedChanege.spec.ts
bricks/diagram/src/draw-canvas/processors/handleNodeContainedChanege.ts
bricks/diagram/src/draw-canvas/reducers/interfaces.ts
bricks/diagram/src/shared/canvas/styles.shadow.css

Closes CMDB_VIEW-230
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 新版拓扑图支持容器元素

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/components/MessageList.tsx

Ref: INFRA-3287
请勾选以下两组选项其中之一：
或者：
>
>

fix(): fix scroll bug

---

bricks/basic/src/bootstrap.ts
bricks/basic/src/data-providers/active-element-blur.spec.ts
bricks/basic/src/data-providers/active-element-blur.ts

feat(): active element blur

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/index.tsx

fix(): make enter interval more efficient

---

bricks/ai/src/chat-view/ChatService.ts

fix(): Browser change tab and stop sse

---

bricks/diagram/docs/eo-display-canvas.md
bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/decorators/DecoratorContainer.tsx
bricks/diagram/src/draw-canvas/decorators/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/asserts.ts
bricks/diagram/src/draw-canvas/processors/computeContainerRect.spec.ts
bricks/diagram/src/draw-canvas/processors/computeContainerRect.ts

Closes CMDB_VIEW-233
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 自动模式，根据containerId关系的节点的位置大小，计算对应容器元素的位置大小

---

bricks/advanced/src/workbench-layout-v2/index.tsx
bricks/advanced/src/workbench-layout-v2/styles.css
bricks/advanced/src/workbench-layout-v2/styles.module.css

Closes POKEMON-762
请勾选以下两组选项其中之一：
或者：
>
>

fix(eo-workbench-layout-v2): 修复拖动时卡死，位置便宜问题

---

bricks/diagram/src/shared/canvas/styles.shadow.css

Refs CMDB_INSTANCE-1767
请勾选以下两组选项其中之一：
或者：
>
>

fix(): Safari  foreignobject render

---

bricks/diagram/package.json
yarn.lock

fix(): update dagre, fix a browser compatibility issue

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/ChatViewContext.ts
bricks/ai/src/chat-view/components/MessageItem/index.tsx
bricks/ai/src/chat-view/components/MessageList.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts

Ref: INFRA-3215
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 支持推荐提问

---

bricks/visual-builder/src/property-editor/components/common/BoxSizeComponent.module.css
bricks/visual-builder/src/property-editor/components/common/BoxSizeComponent.tsx
bricks/visual-builder/src/property-editor/components/common/CodeEditorComponent.tsx
bricks/visual-builder/src/property-editor/components/common/CustomTab.module.css
bricks/visual-builder/src/property-editor/components/common/CustomTab.tsx
bricks/visual-builder/src/property-editor/components/common/InputWithUnitComponent.tsx
bricks/visual-builder/src/property-editor/components/common/UseChildrenSelectComponent.module.css
bricks/visual-builder/src/property-editor/components/common/UseChildrenSelectComponent.tsx
bricks/visual-builder/src/property-editor/index.tsx
bricks/visual-builder/src/property-editor/schema/styles.schema.ts
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.spec.ts
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.ts
bricks/vs/src/code-editor/index.css
bricks/vs/src/code-editor/index.tsx
bricks/vs/src/code-editor/workers/parseYaml.worker.ts

feat(): add Style schema and fix code editor default emit event

---

bricks/containers/src/bootstrap.ts
bricks/containers/src/editors/eo-card/eoCard.schema.ts
bricks/containers/src/editors/eo-card/index.tsx
bricks/containers/src/editors/index.ts
bricks/visual-builder/src/property-editor/components/common/BoxSizeComponent.tsx

feat(): support eo-card editor

---

bricks/basic/src/editors/eo-link/eoLink.schema.tsx
bricks/basic/src/editors/eo-link/index.tsx
bricks/basic/src/editors/index.ts
bricks/icons/src/bootstrap.ts
bricks/icons/src/editors/eo-icon/eoIcon.schema.tsx
bricks/icons/src/editors/eo-icon/index.tsx
bricks/icons/src/editors/index.ts
bricks/visual-builder/src/property-editor/components/common/InputWithUrlComponent.tsx
bricks/visual-builder/src/property-editor/components/common/TextAlignRadioComponent.tsx

feat(): support link & icon editor

---

bricks/form/src/checkbox/checkbox.shadow.css
bricks/form/src/form-item/index.tsx

Closes POKEMON-751
请勾选以下两组选项其中之一：
或者：
>
>

chore(): 选择框构件文本左对齐

---

bricks/basic/src/tooltip/styles.shadow.css

fix(): fix tooltip style

---

bricks/advanced/src/workbench-layout-v2/styles.css
bricks/advanced/src/workbench-layout-v2/styles.module.css

Closes POKEMON-762
请勾选以下两组选项其中之一：
或者：
>
>

fix(eo-workbench-layout-v2): 修复拖动时颜色不对，或者全选字体的问题

---

bricks/basic/src/editors/eo-mini-actions/eoMiniActions.schema.tsx
bricks/basic/src/editors/eo-mini-actions/index.tsx
bricks/basic/src/editors/index.ts
bricks/visual-builder/src/property-editor/components/common/CodeEditorComponent.tsx
bricks/visual-builder/src/property-editor/components/common/ColorPickerComponent.tsx
bricks/visual-builder/src/property-editor/components/common/CustomOptionsComponent.tsx
bricks/visual-builder/src/property-editor/components/common/CutomOptionsComponent.module.css
bricks/visual-builder/src/property-editor/index.tsx
bricks/visual-builder/src/property-editor/utils/formilySchemaFormatter.ts

feat(): add eo-min-actions

---

bricks/ai/package.json
bricks/basic/docs/eo-tag-list.md
bricks/basic/docs/eo-tag.md
bricks/basic/src/tag-list/index.tsx
bricks/basic/src/tag/index.tsx
bricks/basic/src/tag/tag.shadow.css

feat(tag): support outline

---

bricks/advanced/src/workbench-layout-v2/index.tsx

Closes POKEMON-762
请勾选以下两组选项其中之一：
或者：
>
>

fix(eo-workbench-layout-v2): 编辑时点击删除按钮没响应

---

.github/workflows/ci.yml
CONTRIBUTING.md
bricks/visual-builder/test.config.js

chore(ci): fix codecov commit parent

---

bricks/form/src/radio/index.shadow.css

fix(): radio style

---

bricks/nav/src/directory-tree/styles.shadow.css

fix(): 去掉directory-tree样式 refs SHLSTYYWPT-186

---

bricks/visual-builder/src/property-editor/components/AdvancedFormItem/index.tsx
bricks/visual-builder/src/property-editor/components/common/CodeEditorComponent.tsx
bricks/visual-builder/src/property-editor/index.tsx

fix(): property-editor bug

---

bricks/advanced/src/workbench-layout-v2/styles.module.css
bricks/advanced/src/workbench-layout/styles.shadow.css
bricks/form/src/radio/index.shadow.css

fix(): fix firefox style bug

---

bricks/form/src/radio/index.shadow.css

fix(): radio style bug

---

bricks/diagram/src/draw-canvas/processors/asserts.ts
bricks/diagram/src/draw-canvas/processors/handleNodeContainedChange.spec.ts
bricks/diagram/src/draw-canvas/processors/handleNodeContainedChange.ts

Refs CMDB_VIEW-254
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 修复拖动容器,关联的节点不应该触发onContainerContainerChange事件

---

bricks/data-view/docs/progress-bar-list.md
bricks/data-view/src/bootstrap.ts
bricks/data-view/src/progress-bar-list/index.spec.tsx
bricks/data-view/src/progress-bar-list/index.tsx
bricks/data-view/src/progress-bar-list/styles.shadow.css

feat(): CSNSHDP-24 无形资产构件开发-条状图 ref CSNSHDP-24

---

bricks/vs/docs/code-editor.md
bricks/vs/src/code-editor/utils/brickNextSourceMap.ts
bricks/vs/src/code-editor/utils/parseYaml.ts

fix(): codeEditor highlight

---

bricks/diagram/src/draw-canvas/decorators/DecoratorContainer.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/shared/canvas/styles.shadow.css

Refs CMDB_VIEW-254
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 容器名称不更新的问题

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/CodeBlock.shadow.css
bricks/ai/src/chat-view/components/SessionList.tsx
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx
bricks/ai/src/chat-view/styles.shadow.css

Ref: INFRA-3227
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 支持qa.finish和session.change事件

---

bricks/diagram/src/shared/canvas/styles.shadow.css

Refs CMDB_INSTANCE-1774
请勾选以下两组选项其中之一：
或者：
>
>

style(): 横向容器名称从左到右阅读

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts

Ref: INFRA-3321
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 对于敏感词和超过资源配额报错做优化处理

---

bricks/vs/package.json
yarn.lock

fix(): upgrade monaco-editor

---

bricks/api-market/src/apis-directory-tree/Tree.tsx
bricks/api-market/src/apis-directory-tree/index.tsx

fix(): 增加apis-directory-tree操作按钮是否显示字段 refs SHLSTYYWPT-122

---

bricks/form/src/form/index.tsx
shared/form/src/FormStore.spec.ts
shared/form/src/FormStore.ts

Williamcai/shared/form/form store/add name field to validate field return value

---

bricks/basic/src/tag/tag.shadow.css

fix(): fix tag font size

---

bricks/data-view/docs/china-map-chart.md
bricks/data-view/src/china-map-chart/index.tsx
bricks/data-view/src/progress-bar-list/styles.shadow.css

fix(): CSNSHDP-23 资产地图构件开发问题修复 ref CSNSHDP-23

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/index.tsx

Ref: INFRA-3318
请勾选以下两组选项其中之一：
或者：
>
>

fix(): fix ai-chat-view link bug

---

bricks/vs/src/code-editor/index.css

fix(): fix code-editor outline

---

bricks/data-view/src/china-map-chart/index.spec.tsx
bricks/data-view/src/china-map-chart/index.tsx
bricks/data-view/src/china-map-chart/styles.shadow.css

fix(): CSNSHDP-23 地图优化 ref CSNSHDP-23

---

bricks/form/src/select/index.shadow.css

fix(eo-select): only add margin for select options if needed

---

bricks/advanced/src/workbench-layout/index.tsx

Refs DESKTOP-404
请勾选以下两组选项其中之一：
或者：
>
>

fix(workbench-layout): fix layouts data of action.click event detail

---

bricks/form-renderer/src/bootstrap.ts
bricks/form-renderer/src/data-providers/custom-request.spec.ts
bricks/form-renderer/src/data-providers/custom-request.ts

feat(): form-builder custom provider

---

bricks/basic/docs/eo-event-agent.md
bricks/basic/src/bootstrap.ts
bricks/basic/src/event-agent/index.spec.ts
bricks/basic/src/event-agent/index.ts
bricks/basic/src/event-agent/styles.shadow.css
shared/common-bricks/common-bricks.json

feat(): new brick: eo-event-agent

---

bricks/vs/docs/code-editor.md
bricks/vs/src/code-editor/index.css
bricks/vs/src/code-editor/index.tsx

feat(): CodeEditor add placeholder

---

bricks/visual-builder/src/property-editor/components/AdvancedFormItem/AdvancedFormItem.shadow.css
bricks/visual-builder/src/property-editor/components/CategoryTitle/CategoryTitle.shadow.css
bricks/visual-builder/src/property-editor/components/common/ColorPickerComponent.tsx
bricks/visual-builder/src/property-editor/components/common/CustomTab.module.css
bricks/visual-builder/src/property-editor/index.tsx
bricks/visual-builder/src/property-editor/style.css
bricks/visual-builder/src/property-editor/utils/colorTransform.ts
bricks/visual-builder/src/property-editor/utils/colorTrasnform.spec.ts
shared/property-editor/index.d.ts

1. 调整样式
2. 优化颜色选择器
refs NEXT_BUILDER-5207
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 优化属性编辑器

---

bricks/basic/src/editors/eo-next-table/eoNextTable.schema.tsx
bricks/basic/src/editors/eo-next-table/index.tsx
bricks/basic/src/editors/index.ts

Ref: BRICK-463
请勾选以下两组选项其中之一：
或者：
>
>

fix(): add v3 table schema

---

bricks/data-view/src/china-map-chart/index.tsx
bricks/data-view/src/china-map-chart/styles.shadow.css

fix(): CSNSHDP-23 地图文本位置手动调整，缓解重叠问题 ref CSNSHDP-23

---

bricks/visual-builder/src/data-providers/preview/connect.spec.ts
bricks/visual-builder/src/data-providers/preview/connect.ts
bricks/visual-builder/src/data-providers/preview/interfaces.ts

fix(): 恢复 form-builder 相关代码

---

bricks/advanced/src/workbench-layout/index.spec.tsx
bricks/advanced/src/workbench-layout/index.tsx

Refs DESKTOP-410
请勾选以下两组选项其中之一：
或者：
>
>

feat(workbench-layout): add change event

---

bricks/basic/src/editors/eo-descriptions/eoDescriptions.schema.tsx
bricks/basic/src/editors/eo-descriptions/index.tsx
bricks/basic/src/editors/index.ts

Ref: BRICK-315
请勾选以下两组选项其中之一：
或者：
>
>

fix(): v3 desc schema

---

bricks/visual-builder/src/property-editor/index.tsx

fix(): fix property-editor update refresh

---

bricks/basic/src/editors/eo-alert/eoAlert.schema.tsx
bricks/basic/src/editors/eo-alert/index.tsx
bricks/basic/src/editors/eo-next-table/eoNextTable.schema.tsx
bricks/basic/src/editors/index.ts

Ref: BRICK-477
请勾选以下两组选项其中之一：
或者：
>
>

fix(): v3 alert schema

---

bricks/form/src/textarea/index.spec.tsx
bricks/form/src/textarea/index.tsx

fix(textarea): refine default height when auto-size enabled

---

bricks/widget-editors/build.config.js
bricks/widget-editors/package.json
bricks/widget-editors/src/bootstrap.ts
bricks/widget-editors/src/editors/base-layout-v3/index.ts
bricks/widget-editors/src/editors/base-layout-v3/tpl-page-layout/index.tsx
bricks/widget-editors/src/editors/base-layout-v3/tpl-page-layout/tplPageLayout.schema.tsx
bricks/widget-editors/src/editors/base-layout/index.ts
bricks/widget-editors/src/editors/base-layout/tpl-base-page-module/index.tsx
bricks/widget-editors/src/editors/base-layout/tpl-base-page-module/tplPageModule.schema.tsx
bricks/widget-editors/src/editors/index.ts
bricks/widget-editors/src/index.ts
bricks/widget-editors/tsconfig.json

feat(): add widget editors

---

bricks/widget-editors/package.json

chore(): update version

---

bricks/basic/docs/eo-broadcast-channel.md
bricks/basic/package.json
bricks/basic/src/bootstrap.ts
bricks/basic/src/broadcast-channel/index.spec.tsx
bricks/basic/src/broadcast-channel/index.tsx
bricks/basic/src/broadcast-channel/polyfill.ts
bricks/basic/src/broadcast-channel/styles.shadow.css
shared/common-bricks/common-bricks.json
yarn.lock

feat(): new brick: eo-broadcast-channel

---

bricks/advanced/src/next-table/index.tsx
bricks/containers/docs/eo-resizable-box.md
bricks/containers/src/bootstrap.ts
bricks/containers/src/resizable-box/index.spec.tsx
bricks/containers/src/resizable-box/index.tsx
bricks/containers/src/resizable-box/styles.shadow.css
shared/common-bricks/common-bricks.json

feat(): new brick: eo-resizable-box

---

bricks/containers/docs/eo-resizable-box.md
bricks/containers/src/resizable-box/index.tsx

docs(): add an example about direction of eo-resizable-box

---

bricks/recent-history/src/recent-visit/index.tsx

fix(): refine recent-visit tag style

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
bricks/ai/src/chat-view/index.tsx

feat(): chat service add split word flag

---

bricks/advanced/build.config.js
bricks/advanced/package.json
bricks/advanced/src/pdf-viewer/index.tsx
yarn.lock

feat(): pdf-viewer use local worker js

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/markdown.shadow.css

fix(): update markdown style

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/CodeBlock/index.tsx
bricks/ai/src/chat-view/components/MessageItem/Markdown/index.tsx

feat(): chat-view support openAI message

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/index.tsx

fix(): openAI match key

---

bricks/vs/src/code-editor/index.tsx

修复编辑器内容变化时会报 `proxy.findSectionHeaders is not a function` 的错误
请勾选以下两组选项其中之一：
或者：
>
>

fix(): showRegionSectionHeaders/showMarkSectionHeaders specially set to false

---

bricks/ai/src/chat-view/ChatService.ts
bricks/ai/src/chat-view/index.tsx

feat(): chat-view support robotIdChange

---

bricks/illustrations/docs/error-message.md
bricks/illustrations/package.json
bricks/illustrations/src/bootstrap.ts
bricks/illustrations/src/error-message/index.spec.tsx
bricks/illustrations/src/error-message/index.tsx
bricks/illustrations/src/error-message/styles.shadow.css

feat(): new brick: illustrations.error-message

---

bricks/illustrations/src/error-message/index.spec.tsx
bricks/illustrations/src/error-message/index.tsx

fix(error-message): new variant: not-found

---

bricks/basic/src/tooltip/styles.shadow.css
bricks/form/src/form-item/FormItem.shadow.less

fix(): fix form-item labelBrick alignCenter

---

bricks/visual-builder/src/property-editor/index.tsx

fix(): fix property-editor emit value

---

bricks/form/src/form/index.tsx

feat(): form add staticValues

---

bricks/form/src/form-item/FormItem.shadow.less
bricks/form/src/form-item/index.tsx

feat(): update form-item helpBrick

---

bricks/basic/docs/eo-tooltip.md
bricks/basic/src/tooltip/index.tsx

feat(): tooltip add icon

---

bricks/ai/src/chat-view/components/MessageItem/Markdown/index.tsx

feat(): chat-view replace all tool_call

---

bricks/ai/docs/markdown-display.md
bricks/presentational/src/card-item/index.spec.tsx
bricks/presentational/src/card-item/index.tsx
bricks/presentational/src/card-item/styles.shadow.css

fix(eo-card-item): make card-content grow

---

bricks/markdown/docs/eo-markdown-display.md
bricks/markdown/package.json
bricks/markdown/src/bootstrap.ts
bricks/markdown/src/markdown-display/host-context.css
bricks/markdown/src/markdown-display/index.spec.tsx
bricks/markdown/src/markdown-display/index.tsx
bricks/markdown/src/markdown-display/styles.shadow.css
shared/common-bricks/common-bricks.json
shared/markdown/src/MarkdownComponent.tsx

feat(): new brick: eo-markdown-display

---

bricks/basic/docs/show-notification.md
bricks/basic/src/data-providers/show-notification/show-notification.spec.tsx
bricks/basic/src/data-providers/show-notification/show-notification.tsx

fix(show-notification): emit success when notification closed by default

---

bricks/containers/src/modal/index.spec.tsx
bricks/containers/src/modal/index.tsx
bricks/containers/src/modal/modal.shadow.css

Closes CMDB_INSTANCE-1905
请勾选以下两组选项其中之一：
或者：
>
>

feat(modal): add footer slot

---

bricks/ai/src/chat-view/components/MessageList.tsx

fix(): stop message auto-scroll after user manual scrolled

---

bricks/form/src/textarea/index.spec.tsx
bricks/form/src/textarea/index.tsx
bricks/form/src/textarea/textarea.shadow.css

fix(textarea): handle container resize if autoSize enabled

---

bricks/visual-builder/src/raw-data-preview/index.tsx
bricks/visual-builder/src/raw-data-preview/preview.shadow.css

fix(raw-data-preview): show original content

---

bricks/vs/build.config.js
bricks/vs/src/replaces/findSectionHeaders.js

fix(): allow vs code to run on Chrome 89

---

bricks/visual-builder/src/raw-data-preview/index.tsx
bricks/visual-builder/src/raw-data-preview/preview.shadow.css

fix(): refine comment tips

---

bricks/visual-builder/src/raw-data-preview/convert.ts
bricks/visual-builder/src/raw-data-preview/index.tsx

fix(raw-data-preview): add event: view.attr.prompt

---

bricks/form/src/textarea/calculateAutoSizeStyle.ts
bricks/form/src/textarea/textarea.shadow.css

fix(): refine textarea auto size

---

bricks/visual-builder/src/data-providers/prompts/raw-data-date-time.md
bricks/visual-builder/src/data-providers/prompts/raw-data-number.md
bricks/visual-builder/src/raw-data-preview/convert.ts

fix(raw-data-preview): support style for numbers and date-times

---

bricks/vs/package.json
bricks/vs/src/replaces/findSectionHeaders.js
yarn.lock

Reverts easyops-cn/next-bricks#1321

Revert "chore(deps): Update dependency monaco-editor to ^0.51.0"

---

bricks/advanced/docs/eo-text-tooltip.md
bricks/advanced/src/text-tooltip/styles.shadow.css

Closes ITSERVICE_NEXT-8736
请勾选以下两组选项其中之一：
或者：
>
>

style( eo-text-tooltip): 样式调整

---

bricks/basic/src/actions/index.spec.tsx
bricks/basic/src/actions/index.tsx
bricks/basic/src/mini-actions/index.spec.tsx
bricks/basic/src/mini-actions/index.tsx
bricks/basic/src/mini-actions/styles.shadow.css
bricks/presentational/src/card-item/index.tsx

fix(): handle click event for eo-card-item with actions

---

bricks/form/src/form-item/index.tsx
bricks/form/src/input/index.tsx
bricks/form/src/radio/index.tsx
shared/form/src/FormStore.spec.ts
shared/form/src/FormStore.ts

fix(): fix min max validation for eo-input[type=number]

---

bricks/basic/src/tag-list/index.spec.ts
bricks/basic/src/tag-list/index.tsx

Refs NEXT_BUILDER-5288
请勾选以下两组选项其中之一：
或者：
>
>

feat(eo-tag-list): support event: tag.click

---

bricks/basic/package.json
bricks/basic/src/bootstrap.ts
bricks/basic/src/home-redirect/index.spec.ts
bricks/basic/src/home-redirect/index.ts
bricks/basic/src/home-redirect/styles.shadow.css

feat(): new brick: home-redirect

---

bricks/containers/src/page-view/styles.shadow.css

fix(eo-page-view): no min-width for aside

---

bricks/basic/src/data-providers/show-dialog/dialog.module.css

fix(): show-dialog内容过多时，底部按钮看不见 ref CUSTOMIZE-835

---

bricks/nav/src/launchpad-button-v2/MenuGroup.tsx
bricks/nav/src/launchpad-quick-access/index.tsx
bricks/nav/src/launchpad-recent-visits/index.tsx

Refs CUSTOMIZE-800
请勾选以下两组选项其中之一：
或者：
>
>

feat(nav): 支持新开便签跳转页面

---

bricks/nav/src/launchpad-quick-access/index.tsx
bricks/nav/src/launchpad-recent-visits/index.tsx

Refs CUSTOMIZE-800
请勾选以下两组选项其中之一：
或者：
>
>

fix(nav): 配置target新标签页跳转

---

bricks/diagram/src/display-canvas/index.tsx
bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/ConnectLineComponent.tsx
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/EditingLineComponent.tsx
bricks/diagram/src/draw-canvas/HoverStateContext.ts
bricks/diagram/src/draw-canvas/LineConnectorComponent.tsx
bricks/diagram/src/draw-canvas/LineEditorComponent.tsx
bricks/diagram/src/draw-canvas/index.spec.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/handleMouseDown.ts
bricks/diagram/src/shared/canvas/processors/getEditingLinePoints.spec.ts
bricks/diagram/src/shared/canvas/processors/getEditingLinePoints.ts
bricks/diagram/src/shared/canvas/processors/getSmartLinePoints.spec.ts
bricks/diagram/src/shared/canvas/processors/getSmartLinePoints.ts
bricks/diagram/src/shared/canvas/useActiveTarget.ts

feat(): support editing line control points

---

bricks/diagram/src/draw-canvas/CellComponent.tsx
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/EditingLineComponent.tsx
bricks/diagram/src/draw-canvas/LineEditorComponent.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/shared/canvas/processors/getEditingLinePoints.ts
bricks/diagram/src/shared/canvas/processors/getSmartLinePoints.spec.ts
bricks/diagram/src/shared/canvas/processors/getSmartLinePoints.ts

fix(): refine line controls

---

bricks/diagram/docs/eo-draw-canvas.md
bricks/diagram/src/draw-canvas/EdgeComponent.tsx
bricks/diagram/src/draw-canvas/EditingLineComponent.tsx
bricks/diagram/src/draw-canvas/LineConnectorComponent.tsx
bricks/diagram/src/draw-canvas/LineEditorComponent.tsx
bricks/diagram/src/draw-canvas/SmartConnectLineComponent.tsx
bricks/diagram/src/draw-canvas/index.tsx
bricks/diagram/src/draw-canvas/interfaces.ts
bricks/diagram/src/draw-canvas/processors/asserts.ts
bricks/diagram/src/shared/canvas/processors/getConnectLinePoints.spec.ts
bricks/diagram/src/shared/canvas/processors/getConnectLinePoints.ts
bricks/diagram/src/shared/canvas/processors/getEditingLinePoints.spec.ts
bricks/diagram/src/shared/canvas/processors/getEditingLinePoints.ts
bricks/diagram/src/shared/canvas/processors/getSmartLinePoints.spec.ts
bricks/diagram/src/shared/canvas/processors/getSmartLinePoints.ts
bricks/diagram/src/shared/canvas/useLineMarkers.ts

fix(): fix line controls with multiple vertices

---

bricks/basic/src/actions/styles.shadow.css

Refs UISIX-139
请勾选以下两组选项其中之一：
或者：
>
>

fix(): dropdown style

---

bricks/advanced/src/pdf-viewer/index.tsx

fix(): jump to the first match of pre-defined keywords automatically

---

bricks/nav/src/launchpad-button-v2/Launchpad.spec.tsx
bricks/nav/src/launchpad-button-v2/Launchpad.tsx

Closes INFRA-3483
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 售中工单_launchpad-show-open-platform 开关不生效_centos 9 x86

---

bricks/vs/src/code-editor/index.tsx

fix(): do not emit change event when manual setting value

---

cypress/size-check.spec.js

chore(): sort size-check output

---

.github/workflows/ci.yml
bricks/containers/src/page-view/index.tsx
bricks/containers/src/page-view/styles.shadow.css

fix(eo-page-view): move aside slot under top nav bar

---

.github/workflows/ci.yml

chore(ci): show size check result as tables

---

bricks/icons/src/bootstrap.ts
bricks/icons/src/data-providers/get-libs.ts
bricks/icons/src/data-providers/search-icons.ts

fix(): merge icon providers

---

bricks/containers/src/drawer/index.tsx
bricks/containers/src/modal/index.tsx

fix(): do not emit open or close when the state is not changed

---

shared/icons/src/icons/monitor/curve-line.svg
shared/icons/src/icons/monitor/left-circle-arrow.svg
shared/icons/src/icons/monitor/left-solid-arrow.svg
shared/icons/src/icons/monitor/polyline-line.svg
shared/icons/src/icons/monitor/right-circle-arrow.svg
shared/icons/src/icons/monitor/right-solid-arrow.svg
shared/icons/src/icons/monitor/straight-line.svg

Refs CMDB_CONSUME-426
请勾选以下两组选项其中之一：
或者：
>
>

chore(): add icon

---

bricks/form/src/select/index.tsx

fix(eo-select): search event respects debounceSearchDelay

---

shared/icons/src/icons/expand.svg
shared/icons/src/icons/share.svg
shared/icons/src/icons/shrink.svg

feat(): add some icons

---

shared/icons/src/icons/replay.svg

feat(): new icon: replay
